const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),ts=require('typescript');
const root=process.cwd()+'/';let time=Date.now();const FakeDate=class extends Date{static now(){return time}};
function load(file,deps={}){const module={exports:{}};const code=ts.transpileModule(fs.readFileSync(root+file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{module,exports:module.exports,require:n=>deps[n],Date:FakeDate,crypto:global.crypto,Response,console});return module.exports;}
const runner=load('lib/runner.ts'),garden=load('lib/garden.ts');const g=load('lib/game.ts',{'./runner':runner,'./garden':garden,'./fishing':load('lib/fishing.ts')});
const p=()=>[g.player('Bunny',time),g.player('Turtle',time)];
function setup(game){const s=g.createState(p()[0]);s.players=p();g.reset(s,game);g.act(s,0,{action:'ready'},time);g.act(s,1,{action:'ready'},time);time=s.start+10000;return s;}
function doMove(s,me,action,extra={}){g.act(s,me,{action,round:s.round,expected:s.moves,...extra},time);}
for(const game of g.games){const s=setup(game.id);
 if(game.id==='fishing'){for(let i=0;i<6;i++){doMove(s,0,'fish',{value:'cast'});time=s.anglers[0].biteAt+100;doMove(s,0,'fish',{value:'reel'});}}
 if(game.id==='garden'){for(let i=0;i<12;i++){doMove(s,i%2,'garden',{value:'plant',cell:i%16,choice:'daisy'});assert.throws(()=>doMove(s,0,'garden',{value:'harvest',cell:i%16}),/growing/);doMove(s,1,'garden',{value:'water',cell:i%16});time=s.garden.plots[i%16].readyAt;doMove(s,1-i%2,'garden',{value:'harvest',cell:i%16});}}
 if(game.id==='race'){s.runners[0].distance=239.9;s.runners[1].distance=220;g.tick(s,time+1000);}
 if(game.id==='hearts')for(let i=0;i<12;i++)doMove(s,0,'heart',{expected:i,cell:(i*7+s.round*3)%9});
 if(game.id==='reaction'){doMove(s,0,'react',{ms:240});doMove(s,1,'react',{ms:330});}
 if(game.id==='rps'){doMove(s,0,'choose',{choice:'rock'});assert.equal(g.publicState(s,1).players[0].choice,'locked');doMove(s,1,'choose',{choice:'scissors'});}
 if(game.id==='ttt'){s.turn=0;for(const [i,cell] of [[0,0],[1,3],[0,1],[1,4],[0,2]])doMove(s,i,'move',{cell});}
 if(game.id==='connect'){s.turn=0;for(const [i,cell] of [[0,0],[1,1],[0,0],[1,1],[0,0],[1,1],[0,0]])doMove(s,i,'drop',{cell});}
 if(game.id==='number'){assert.equal(g.publicState(s,0).number.secret,0);s.turn=0;doMove(s,0,'guess',{value:String(s.number.secret)});}
 if(game.id==='words'){assert.equal(g.publicState(s,0).word.answer,'');doMove(s,0,'answer',{value:s.word.answer});}
 if(game.id==='sync'){doMove(s,0,'choose',{choice:'🧸'});assert.equal(g.publicState(s,1).players[0].choice,'locked');doMove(s,1,'choose',{choice:'🧸'});}
 if(game.id==='memory'){s.turn=0;assert(g.publicState(s,0).memory.deck.every(x=>x==='?'));const pairs=new Map();s.memory.deck.forEach((v,i)=>pairs.set(v,[...(pairs.get(v)||[]),i]));for(const pair of pairs.values()){doMove(s,0,'flip',{cell:pair[0]});doMove(s,0,'flip',{cell:pair[1]});}}
 assert.equal(s.finished,true,game.id);assert.equal(s.winner,['sync','garden'].includes(game.id)?-2:0,game.id);assert.equal(s.players[0].score,['sync','garden'].includes(game.id)?2:3);assert.equal(s.history.length,1);const score=s.players[0].score;g.tick(s,time+999999);assert.equal(s.players[0].score,score,'score not awarded twice');g.act(s,0,{action:'ready'},time);assert.equal(s.finished,false);assert.equal(s.players[0].score,score);assert.equal(s.players[1].ready,false);console.log(game.id+': win, private state, persistent room score, rematch passed');
}
{
 const s=setup('memory');s.turn=0;const a=0,b=s.memory.deck.findIndex(x=>x!==s.memory.deck[0]);doMove(s,0,'flip',{cell:a});doMove(s,0,'flip',{cell:b});assert.throws(()=>doMove(s,0,'flip',{cell:15}),/Wait/);g.tick(s,time+1601);assert.equal(s.turn,1);assert.equal(s.memory.flipped.length,0);assert.throws(()=>doMove(s,0,'flip',{cell:0}),/partner/);
}
{
 const s=setup('connect');s.turn=0;doMove(s,0,'drop',{cell:0});assert.throws(()=>doMove(s,0,'drop',{cell:1}),/partner/);assert.throws(()=>doMove(s,1,'drop',{cell:1,expected:0}),/board changed/);assert.throws(()=>doMove(s,1,'drop',{cell:1,round:s.round-1}),/new round/);
 g.act(s,0,{action:'abort'},time);g.act(s,1,{action:'abort'},time);assert.equal(s.winner,-3);assert.equal(s.players[0].score,0);
}
{
 const s=setup('rps');const id=crypto.randomUUID();doMove(s,0,'choose',{choice:'rock',requestId:id});doMove(s,1,'choose',{choice:'paper'});g.act(s,0,{action:'ready',requestId:'same-ready'},time);const r=s.round;g.act(s,0,{action:'ready',requestId:'same-ready'},time);assert.equal(s.round,r);
}
{const a=garden.newGarden();assert.throws(()=>garden.gardenMove(a,0,'plant',16,'daisy',time),/plot/);assert.throws(()=>garden.gardenMove(a,0,'plant',0,'moon',time),/level 2/);assert.throws(()=>garden.gardenMove(a,0,'upgrade',0,'',time),/20/);garden.gardenMove(a,0,'plant',0,'daisy',time);assert.throws(()=>garden.gardenMove(a,1,'plant',0,'rose',time),/already/);garden.gardenMove(a,1,'water',0,'',time);const ready=a.plots[0].readyAt;assert.throws(()=>garden.gardenMove(a,0,'water',0,'',time),/already/);assert.equal(a.plots[0].readyAt,ready);const restored=JSON.parse(JSON.stringify(a));garden.gardenMove(restored,0,'harvest',0,'',ready);assert.equal(restored.coins,19);assert.equal(restored.harvests,1);restored.coins=40;garden.gardenMove(restored,0,'upgrade',0,'',time);restored.weather='rain';garden.gardenMove(restored,0,'plant',1,'moon',time);assert.equal(restored.plots[1].readyAt-time,Math.round(45000*.85*.7));console.log('Garden growth, shared plot conflicts, economy, upgrades, rain and saved-state restoration passed');}
{const f=load('lib/fishing.ts'),a=f.newAngler();assert.throws(()=>f.fishMove(a,'reel',time),/Cast/);f.fishMove(a,'cast',time);assert.throws(()=>f.fishMove(a,'cast',time+1),/already/);f.fishMove(a,'reel',a.biteAt-1);assert.equal(a.catches,0);f.fishMove(a,'cast',time+5000);f.fishMove(a,'reel',a.closesAt+1);assert.equal(a.catches,0);for(let i=0;i<3;i++){f.fishMove(a,'cast',time+10000+i*5000);f.fishMove(a,'reel',a.biteAt);}assert.equal(a.combo,3);assert.equal(a.collection.length,3);assert.equal(a.points,7);assert.equal(garden.restoreGarden({...garden.newGarden(),frogCells:[-1,20]}),null);assert.equal(garden.restoreGarden({...garden.newGarden(),plots:[{seed:'invalid'}]}),null);assert(garden.restoreGarden(JSON.parse(JSON.stringify(garden.newGarden()))));console.log('Fishing timing, duplicate casts, combos, collection and corrupt garden saves passed');}
let rows=new Map();const db={prepare(sql){return{bind(...args){return{async first(){const r=rows.get(args[0]);return r&&r.expires>args[1]?{...r}:null},async run(){if(sql.startsWith('INSERT')){rows.set(args[0],{state:args[1],revision:0,expires:args[2]});return{meta:{changes:1}};}const r=rows.get(args[1]);if(r.revision!==args[2])return{meta:{changes:0}};r.state=args[0];r.revision++;return{meta:{changes:1}};}};}};}};
const {POST}=load('app/api/game/route.ts',{'zod':require('zod'),'@/lib/game':g,'@/lib/db':{db:()=>db}});
async function call(body){const r=await POST({json:async()=>body});return{...(await r.json()),status:r.status};}
(async()=>{const malformed=await POST({json:async()=>{throw new SyntaxError('bad json')}});assert.equal(malformed.status,400);const a=await call({action:'create',name:'A'});const [b,c]=await Promise.all([call({action:'join',code:a.code,name:'B'}),call({action:'join',code:a.code,name:'C'})]);assert.deepEqual([b.status,c.status].sort(),[200,409]);const auth={code:a.code,token:a.token};const d=await call({...auth,action:'state'});assert(!JSON.stringify(d.state).includes(a.token));const e=await call({...auth,action:'state'});assert.equal(e.revision,d.revision,'polls do not write unchanged data');assert.equal((await call({action:'state',code:a.code,token:'fake'})).status,403);assert.equal((await call({action:'move',code:a.code,token:a.token,cell:'bad'})).status,400);console.log('Concurrent room join, two-player limit, auth, validation, read-only polling passed');})().catch(e=>{console.error(e);process.exit(1)});
