const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),ts=require('typescript'),assert=require('node:assert/strict');
let now=Date.UTC(2026,8,14,12),fetches=0,fail=false;const cache=new Map();
const FakeDate=class extends Date{static now(){return now}};
const mockFetch=async()=>{fetches++;if(fail)throw Error('offline');return {ok:true,json:async()=>({current:{weather_code:63,temperature_2m:27,apparent_temperature:29,relative_humidity_2m:85,wind_speed_10m:20,is_day:1},daily:{sunrise:[now/1000-21600],sunset:[now/1000+21600]}})}};
const rows=new Map();const database={prepare(sql){return{bind(...a){return{async first(){if(sql.includes('weather_cache'))return null;const r=rows.get(a[0]);return r&&r.expires>a[1]?{...r}:null},async run(){if(sql.includes('weather_cache'))return {meta:{changes:1}};if(sql.startsWith('INSERT')){rows.set(a[0],{state:a[1],revision:0,expires:a[2]});return {meta:{changes:1}};}const r=rows.get(a[1]);if(r.revision!==a[2])return {meta:{changes:0}};r.state=a[0];r.revision++;return {meta:{changes:1}};}}}}}};
function load(file){if(cache.has(file))return cache.get(file);const m={exports:{}};cache.set(file,m.exports);const requireModule=n=>n==='@/lib/db'?{db:()=>database}:n.startsWith('@/')?load(n.slice(2)+'.ts'):n.startsWith('.')?load(path.posix.normalize(path.posix.dirname(file)+'/'+n)+'.ts'):require(n);const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{module:m,exports:m.exports,require:requireModule,Date:FakeDate,Intl,crypto:global.crypto,Response,URLSearchParams,AbortSignal,fetch:mockFetch,console});return m.exports;}
(async()=>{const map=load('services/weather/weather.mapper.ts'),adapter=load('services/weather/weather.adapter.ts');for(const [code,type] of [[0,'clear'],[2,'partly_cloudy'],[3,'cloudy'],[45,'fog'],[51,'light_rain'],[63,'rain'],[65,'heavy_rain'],[95,'thunderstorm'],[71,'light_snow'],[73,'snow'],[75,'heavy_snow']])assert.equal(adapter.mapWmo(code),type);assert.equal(adapter.mapWmo(0,40),'windy');assert.equal(adapter.mapWmo(95,40),'thunderstorm');assert.throws(()=>adapter.WeatherAdapter.normalize({},now));
const loc={city:'Tokyo',country:'Japan',countryCode:'JP',latitude:35.68,longitude:139.69,timezone:'Asia/Tokyo',selectedAt:now};assert.equal(map.localClock(loc,Date.UTC(2026,8,14,12)),'21:00');assert.equal(map.season(loc,Date.UTC(2026,11,15)),'Winter');assert.equal(map.season({...loc,latitude:-33,timezone:'Australia/Sydney'},Date.UTC(2026,11,15)),'Summer');assert.equal(map.season({...loc,latitude:6.9},now),'Tropical');assert.equal(map.temperatureBand(-6),'Extreme cold');assert.equal(map.temperatureBand(33),'Hot');
const service=load('services/weather/weather.service.ts');const [a,b]=await Promise.all([service.weatherFor(loc),service.weatherFor(loc)]);assert.equal(fetches,1,'concurrent requests share a provider call');assert.equal(a.type,'rain');assert.equal(a.sunset,now+21600000);fail=true;now+=1200001;const stale=await service.weatherFor(loc);assert.equal(stale.type,'rain');assert.equal(stale.unavailable,true);const fallback=await service.weatherFor({...loc,latitude:0});assert.equal(fallback.type,'partly_cloudy');assert.equal(fallback.temperature,null);
fail=false;const api=load('app/api/game/route.ts');const call=async b=>{const r=await api.POST({json:async()=>b});return {...await r.json(),status:r.status}};const p=await call({action:'create',location:loc,name:'One'});const q=await call({action:'join',code:p.code,name:'Two'});const auth={code:p.code,token:p.token},auth2={code:p.code,token:q.token};assert.equal(p.status,200);const newLoc={...loc,city:'Colombo',country:'Sri Lanka',countryCode:'LK',latitude:6.9,longitude:79.8,timezone:'Asia/Colombo'};const proposal=await call({...auth,action:'world_propose',location:newLoc});assert.equal(proposal.state.world.current.location.city,'Tokyo');const id=proposal.state.world.proposal.id;assert.equal((await call({...auth,action:'world_accept',proposalId:id})).status,409);const accepted=await call({...auth2,action:'world_accept',proposalId:id});assert.equal(accepted.state.world.current.location.city,'Colombo');const view=await call({...auth,action:'state'});assert.deepEqual(JSON.stringify(accepted.state.world.current),JSON.stringify(view.state.world.current));assert.equal((await call({...auth,action:'world_accept',proposalId:id})).status,409);const requestId=crypto.randomUUID();const first=await call({...auth,action:'world_collect',requestId});const again=await call({...auth,action:'world_collect',requestId});assert.deepEqual(first.state.world.inventory,again.state.world.inventory);assert.equal((await call({...auth2,action:'world_collect'})).status,409);const reject=await call({...auth,action:'world_propose',location:loc});await call({...auth2,action:'world_decline',proposalId:reject.state.world.proposal.id});assert.equal((await call({...auth,action:'state'})).state.world.current.location.city,'Colombo');
console.log('Weather: all mappings, timezone, hemisphere, cache deduplication, stale fallback, shared consent, synchronized state, decline and reward idempotency passed');})().catch(e=>{console.error(e);process.exit(1)});
