const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const els = {
  homeView:$('#homeView'),roomView:$('#roomView'),gameView:$('#gameView'),playerName:$('#playerName'),roomCodeInput:$('#roomCodeInput'),createRoomBtn:$('#createRoomBtn'),joinRoomBtn:$('#joinRoomBtn'),leaveRoomBtn:$('#leaveRoomBtn'),copyRoomBtn:$('#copyRoomBtn'),backToRoomBtn:$('#backToRoomBtn'),connectionStatus:$('#connectionStatus'),statusText:$('#statusText'),roomCodeDisplay:$('#roomCodeDisplay'),myName:$('#myName'),myAvatar:$('#myAvatar'),opponentName:$('#opponentName'),opponentAvatar:$('#opponentAvatar'),opponentReadyText:$('#opponentReadyText'),hostHint:$('#hostHint'),gameTitle:$('#gameTitle'),gameStage:$('#gameStage'),sessionScoreMe:$('#sessionScoreMe'),sessionScoreThem:$('#sessionScoreThem'),toast:$('#toast')
};
const GAME_TITLES={froggy:'Froggy Garden',connect4:'Connect Four',memory:'Memory Match',tictac:'Tic-Tac-Toe',tap:'Tap Rush',reaction:'Reaction Duel',rps:'RPS Arena',word:'Word Race'};
const ICE_CONFIG={iceServers:[
  {urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'},{urls:'stun:stun.cloudflare.com:3478'},{urls:'stun:webrtc.homeway.io:443'},
  {urls:'turn:webrtc.homeway.io:443?transport=udp'},{urls:'turn:webrtc.homeway.io:3478?transport=tcp'},{urls:'turns:webrtc.homeway.io:443?transport=tcp'},
  {urls:'turn:openrelay.metered.ca:80',username:'openrelayproject',credential:'openrelayproject'},{urls:'turn:openrelay.metered.ca:443?transport=tcp',username:'openrelayproject',credential:'openrelayproject'}
],iceCandidatePoolSize:10,sdpSemantics:'unified-plan'};
const state={peer:null,conn:null,isHost:false,roomCode:'',name:'',opponentName:'',currentGame:null,scoreMe:0,scoreThem:0,connectAttempt:0,connectTimer:null,tap:{},reaction:{},rps:{},tictac:{},connect4:{},memory:{},froggy:{},word:{}};
let toastTimer,tapTimer,tapCountdown,reactionTimer,memoryTimer;
function myRole(){return state.isHost?'host':'guest'} function otherRole(){return state.isHost?'guest':'host'}
function peerId(code){return `tap-together-v2-${code}`} function sanitizeName(v){return ((v||'').trim().replace(/[<>]/g,'').slice(0,18)||'Player')}
function escapeHtml(v){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML}
function showToast(m){els.toast.textContent=m;els.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>els.toast.classList.remove('show'),2400)}
function setStatus(s,t){els.connectionStatus.dataset.state=s;els.statusText.textContent=t} function showView(v){[els.homeView,els.roomView,els.gameView].forEach(x=>x.classList.remove('active'));v.classList.add('active')}
function generateCode(){const c='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:6},()=>c[Math.floor(Math.random()*c.length)]).join('')}
function saveName(){state.name=sanitizeName(els.playerName.value);els.playerName.value=state.name;localStorage.setItem('tapTogetherName',state.name)}
function updateScores(){els.sessionScoreMe.textContent=state.scoreMe;els.sessionScoreThem.textContent=state.scoreThem} function awardRole(r){if(!r||r==='draw')return;if(r===myRole())state.scoreMe++;else state.scoreThem++;updateScores()}
function clearTimers(){clearInterval(tapTimer);clearTimeout(tapCountdown);clearTimeout(reactionTimer);clearTimeout(memoryTimer);clearTimeout(state.connectTimer);tapTimer=tapCountdown=reactionTimer=memoryTimer=null}
function updateRoomUI(){
  els.roomCodeDisplay.textContent=state.roomCode||'------';els.myName.textContent=state.name||'Player';els.myAvatar.textContent=(state.name||'P')[0].toUpperCase();const ok=!!(state.conn&&state.conn.open);
  if(state.opponentName&&ok){els.opponentName.textContent=state.opponentName;els.opponentAvatar.textContent=state.opponentName[0].toUpperCase();els.opponentAvatar.classList.remove('muted');els.opponentReadyText.textContent='Connected';els.hostHint.textContent='Connected — choose any game'}
  else{els.opponentName.textContent='Waiting…';els.opponentAvatar.textContent='?';els.opponentAvatar.classList.add('muted');els.opponentReadyText.textContent=state.isHost?'Share the code':`Connecting${'.'.repeat((state.connectAttempt%3)+1)}`;els.hostHint.textContent=state.isHost?'Waiting for another player':'Joining room…'}
  $$('.game-card').forEach(b=>b.disabled=!ok)
}
function makePeer(id){return new Peer(id,{host:'0.peerjs.com',port:443,path:'/',secure:true,debug:1,pingInterval:3000,config:ICE_CONFIG})}
function send(data){if(state.conn&&state.conn.open){state.conn.send(data);return true}showToast('Connection lost. Reconnecting…');return false}
function setupConnection(conn){
  if(state.conn&&state.conn!==conn){try{state.conn.close()}catch(_){}}state.conn=conn;
  conn.on('open',()=>{clearTimeout(state.connectTimer);state.connectAttempt=0;setStatus('online','Connected');send({type:'HELLO',name:state.name});updateRoomUI();showToast('Connected. Games are unlocked.')});
  conn.on('data',handleMessage);conn.on('close',()=>{state.opponentName='';state.conn=null;setStatus('connecting',state.isHost?'Waiting':'Reconnecting');updateRoomUI();if(!state.isHost&&state.peer&&!state.peer.destroyed)scheduleJoinRetry()});
  conn.on('error',e=>{console.warn('Data connection error',e);if(!state.isHost)scheduleJoinRetry()})
}
function attachPeerEvents(peer){peer.on('connection',conn=>{if(!state.isHost)return conn.close();setupConnection(conn)});peer.on('disconnected',()=>{setStatus('connecting','Reconnecting');try{if(!peer.destroyed)peer.reconnect()}catch(_){}});peer.on('error',e=>{console.warn('Peer error',e);if(e.type==='unavailable-id')showToast('Room code collision. Create another room.');else if(e.type==='peer-unavailable')showToast('Room not found yet. Retrying…');else if(e.type!=='disconnected')showToast('Network handshake failed. Retrying…')})}
function connectToHost(){if(!state.peer||state.peer.destroyed||state.isHost)return;state.connectAttempt++;setStatus('connecting',`Connecting ${state.connectAttempt}/5`);updateRoomUI();const conn=state.peer.connect(peerId(state.roomCode),{reliable:true,serialization:'json'});setupConnection(conn);clearTimeout(state.connectTimer);state.connectTimer=setTimeout(()=>{if(state.conn&&state.conn.open)return;try{conn.close()}catch(_){}if(state.connectAttempt<5)connectToHost();else{setStatus('offline','Could not connect');showToast('Could not connect. Try switching Wi‑Fi/mobile data and retry.')}},9000)}
function scheduleJoinRetry(){clearTimeout(state.connectTimer);if(state.connectAttempt<5)state.connectTimer=setTimeout(connectToHost,1200)}
function createRoom(){if(typeof Peer==='undefined')return showToast('Multiplayer library did not load. Refresh.');saveName();disconnect(false);state.isHost=true;state.roomCode=generateCode();setStatus('connecting','Opening room');state.peer=makePeer(peerId(state.roomCode));attachPeerEvents(state.peer);state.peer.on('open',()=>{setStatus('connecting','Waiting');updateRoomUI();showView(els.roomView);const u=new URL(location.href);u.searchParams.set('room',state.roomCode);history.replaceState({},'',u)})}
function joinRoom(){if(typeof Peer==='undefined')return showToast('Multiplayer library did not load. Refresh.');const code=els.roomCodeInput.value.trim().toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);if(code.length!==6)return showToast('Enter the 6-character room code.');saveName();disconnect(false);state.isHost=false;state.roomCode=code;state.connectAttempt=0;setStatus('connecting','Connecting');updateRoomUI();showView(els.roomView);state.peer=makePeer();attachPeerEvents(state.peer);state.peer.on('open',connectToHost)}
function disconnect(home=true){clearTimers();try{state.conn?.close()}catch(_){}try{state.peer?.destroy()}catch(_){}Object.assign(state,{peer:null,conn:null,opponentName:'',currentGame:null,roomCode:'',scoreMe:0,scoreThem:0,connectAttempt:0});setStatus('offline','Offline');updateScores();if(home){history.replaceState({},'',location.pathname);showView(els.homeView)}}
function gameSetup(g){if(g==='froggy')return{tiles:Array.from({length:12},(_,i)=>i<8?'weed':'empty').sort(()=>Math.random()-.5),tokens:0};if(g==='memory'){const i=['🍓','⭐','🐸','🌙','🍄','🎈','🍋','💎'];return{deck:[...i,...i].sort(()=>Math.random()-.5)}}if(g==='word')return makeWordRound();return{}}
function startGame(g){if(!GAME_TITLES[g]||!(state.conn&&state.conn.open))return showToast('Wait until both players show Connected.');const setup=gameSetup(g);openGame(g,true,setup);send({type:'GAME_START',game:g,setup})}
function openGame(g,local,setup={}){if(!GAME_TITLES[g])return;clearTimers();state.currentGame=g;state.scoreMe=0;state.scoreThem=0;updateScores();els.gameTitle.textContent=GAME_TITLES[g];showView(els.gameView);const renderers={froggy:renderFroggy,connect4:renderConnect4,memory:renderMemory,tictac:renderTicTac,tap:renderTap,reaction:renderReaction,rps:renderRps,word:renderWord};renderers[g](setup);if(!local)showToast(`${state.opponentName||'Opponent'} opened ${GAME_TITLES[g]}.`)}
function handleMessage(m){if(!m||typeof m!=='object')return;switch(m.type){case'HELLO':state.opponentName=sanitizeName(m.name);updateRoomUI();break;case'GAME_START':openGame(m.game,false,m.setup||{});break;case'EXIT_GAME':state.currentGame=null;clearTimers();showView(els.roomView);showToast('Opponent returned to the game shelf.');break;case'TIC_MOVE':applyTicMove(m.index,m.role);break;case'TIC_RESET':resetTic(false);break;case'C4_MOVE':applyC4Move(m.col,m.role);break;case'C4_RESET':resetC4(false);break;case'MEM_FLIP':applyMemoryFlip(m.index,m.role);break;case'MEM_RESET':resetMemory(m.setup,false);break;case'FROG_ACTION':if(state.isHost)hostFrogAction(m);break;case'FROG_STATE':state.froggy.tiles=m.tiles;state.froggy.tokens=m.tokens;renderFrogBoard();break;case'TAP_START':prepareTap(m.delay||900);break;case'TAP_SCORE':receiveTapScore(m.score);break;case'TAP_DONE':receiveTapDone(m.score);break;case'REACT_START':prepareReaction(m.delay);break;case'REACT_RESULT':receiveReactionResult(m.value);break;case'RPS_CHOICE':receiveRps(m.choice);break;case'RPS_RESET':resetRps(false);break;case'WORD_CLAIM':if(state.isHost)hostWordClaim(m.answer,m.role);break;case'WORD_RESULT':finishWord(m.winner);break;case'WORD_NEW':resetWord(m.setup,false)}}
els.createRoomBtn.addEventListener('click',createRoom);els.joinRoomBtn.addEventListener('click',joinRoom);els.leaveRoomBtn.addEventListener('click',()=>disconnect(true));els.copyRoomBtn.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(state.roomCode);showToast('Room code copied.')}catch(_){showToast(state.roomCode)}});els.backToRoomBtn.addEventListener('click',()=>{if(state.currentGame)send({type:'EXIT_GAME'});state.currentGame=null;clearTimers();showView(els.roomView)});$$('.game-card').forEach(b=>b.addEventListener('click',()=>startGame(b.dataset.game)));els.roomCodeInput.addEventListener('keydown',e=>{if(e.key==='Enter')joinRoom()});window.addEventListener('beforeunload',()=>{try{state.conn?.close();state.peer?.destroy()}catch(_){}});const saved=localStorage.getItem('tapTogetherName');if(saved)els.playerName.value=saved;const qp=new URLSearchParams(location.search).get('room');if(qp)els.roomCodeInput.value=qp.toUpperCase().slice(0,6);updateRoomUI();