function renderTicTac(){state.tictac={board:Array(9).fill(''),turn:'host',done:false};els.gameStage.innerHTML=`<span class="eyebrow">Turn based</span><h2>Tic-Tac-Toe</h2><p id="ticStatus"></p><div class="board3" id="ticBoard"></div><div class="round-actions"><button class="btn secondary" id="ticReset">New round</button></div>`;$('#ticReset').onclick=()=>resetTic(true);renderTic()}
function renderTic(){const b=$('#ticBoard');if(!b)return;$('#ticStatus').textContent=state.tictac.done?'Round finished':state.tictac.turn===myRole()?'Your turn':'Opponent’s turn';b.innerHTML=state.tictac.board.map((v,i)=>`<button class="cell3" data-i="${i}" ${v||state.tictac.done||state.tictac.turn!==myRole()?'disabled':''}>${v}</button>`).join('');b.querySelectorAll('.cell3').forEach(c=>c.onclick=()=>{const i=Number(c.dataset.i);send({type:'TIC_MOVE',index:i,role:myRole()});applyTicMove(i,myRole())})}
function applyTicMove(i,role){if(state.currentGame!=='tictac'||state.tictac.done||state.tictac.turn!==role||state.tictac.board[i])return;state.tictac.board[i]=role==='host'?'X':'O';if(winner3(state.tictac.board)){state.tictac.done=true;awardRole(role);showToast(role===myRole()?'You win!':'Opponent wins.')}else if(state.tictac.board.every(Boolean)){state.tictac.done=true;showToast('Draw.')}else state.tictac.turn=role==='host'?'guest':'host';renderTic()}
function winner3(b){return[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(([a,c,d])=>b[a]&&b[a]===b[c]&&b[a]===b[d])} function resetTic(n){state.tictac={board:Array(9).fill(''),turn:'host',done:false};if(n)send({type:'TIC_RESET'});renderTic()}
function renderConnect4(){state.connect4={board:Array.from({length:6},()=>Array(7).fill('')),turn:'host',done:false};els.gameStage.innerHTML=`<span class="eyebrow">Strategy duel</span><h2>Connect Four</h2><p id="c4Status"></p><div class="c4" id="c4Board"></div><div class="round-actions"><button class="btn secondary" id="c4Reset">New round</button></div>`;$('#c4Reset').onclick=()=>resetC4(true);renderC4()}
function renderC4(){const root=$('#c4Board');if(!root)return;$('#c4Status').textContent=state.connect4.done?'Round finished':state.connect4.turn===myRole()?'Your turn — tap a column':'Opponent’s turn';root.innerHTML=state.connect4.board.flatMap(row=>row.map((v,c)=>`<button class="c4cell ${v||''}" data-c="${c}"></button>`)).join('');root.querySelectorAll('.c4cell').forEach(x=>x.onclick=()=>{if(state.connect4.turn!==myRole()||state.connect4.done)return;const c=Number(x.dataset.c);send({type:'C4_MOVE',col:c,role:myRole()});applyC4Move(c,myRole())})}
function applyC4Move(col,role){if(state.currentGame!=='connect4'||state.connect4.done||state.connect4.turn!==role)return;let r=5;while(r>=0&&state.connect4.board[r][col])r--;if(r<0)return;state.connect4.board[r][col]=role==='host'?'red':'yellow';if(c4Winner(state.connect4.board,r,col)){state.connect4.done=true;awardRole(role);showToast(role===myRole()?'You win!':'Opponent wins.')}else if(state.connect4.board.every(row=>row.every(Boolean))){state.connect4.done=true;showToast('Draw.')}else state.connect4.turn=role==='host'?'guest':'host';renderC4()}
function c4Winner(b,r,c){const v=b[r][c];return[[1,0],[0,1],[1,1],[1,-1]].some(([dr,dc])=>{let n=1;for(const s of[-1,1]){let rr=r+dr*s,cc=c+dc*s;while(rr>=0&&rr<6&&cc>=0&&cc<7&&b[rr][cc]===v){n++;rr+=dr*s;cc+=dc*s}}return n>=4})} function resetC4(n){state.connect4={board:Array.from({length:6},()=>Array(7).fill('')),turn:'host',done:false};if(n)send({type:'C4_RESET'});renderC4()}
function renderMemory(setup={}){state.memory={deck:(setup.deck||[]).slice(),open:[],matched:new Set(),turn:'host',pairs:{host:0,guest:0},lock:false,done:false};els.gameStage.innerHTML=`<span class="eyebrow">Memory duel</span><h2>Memory Match</h2><p id="memStatus"></p><div class="duel-board"><div class="duel-stat"><small>You</small><strong id="memMe">0</strong></div><div class="duel-stat"><small>${escapeHtml(state.opponentName||'Opponent')}</small><strong id="memThem">0</strong></div></div><div class="memory-grid" id="memGrid"></div><div class="round-actions"><button class="btn secondary" id="memReset">Shuffle & restart</button></div>`;$('#memReset').onclick=()=>{const s=gameSetup('memory');resetMemory(s,true)};renderMemoryBoard()}
function renderMemoryBoard(){const g=$('#memGrid');if(!g)return;$('#memStatus').textContent=state.memory.done?'Round finished':state.memory.turn===myRole()?'Your turn':'Opponent’s turn';$('#memMe').textContent=state.memory.pairs[myRole()];$('#memThem').textContent=state.memory.pairs[otherRole()];g.innerHTML=state.memory.deck.map((v,i)=>`<button class="memory-card ${state.memory.open.includes(i)?'open':''} ${state.memory.matched.has(i)?'matched':''}" data-i="${i}" ${state.memory.lock||state.memory.done||state.memory.turn!==myRole()||state.memory.matched.has(i)||state.memory.open.includes(i)?'disabled':''}>${v}</button>`).join('');g.querySelectorAll('.memory-card').forEach(c=>c.onclick=()=>{const i=Number(c.dataset.i);send({type:'MEM_FLIP',index:i,role:myRole()});applyMemoryFlip(i,myRole())})}
function applyMemoryFlip(i,role){if(state.currentGame!=='memory'||state.memory.done||state.memory.lock||state.memory.turn!==role||state.memory.matched.has(i)||state.memory.open.includes(i))return;state.memory.open.push(i);renderMemoryBoard();if(state.memory.open.length===2){state.memory.lock=true;const[a,b]=state.memory.open;if(state.memory.deck[a]===state.memory.deck[b])memoryTimer=setTimeout(()=>{state.memory.matched.add(a);state.memory.matched.add(b);state.memory.pairs[role]++;state.memory.open=[];state.memory.lock=false;if(state.memory.matched.size===state.memory.deck.length){state.memory.done=true;const h=state.memory.pairs.host,g=state.memory.pairs.guest;if(h!==g)awardRole(h>g?'host':'guest');showToast(h===g?'Draw.':state.memory.pairs[myRole()]>state.memory.pairs[otherRole()]?'You win!':'Opponent wins.')}renderMemoryBoard()},550);else memoryTimer=setTimeout(()=>{state.memory.open=[];state.memory.lock=false;state.memory.turn=role==='host'?'guest':'host';renderMemoryBoard()},850)}}
function resetMemory(setup,n){state.memory={deck:setup.deck.slice(),open:[],matched:new Set(),turn:'host',pairs:{host:0,guest:0},lock:false,done:false};if(n)send({type:'MEM_RESET',setup});renderMemoryBoard()}
