'use client';
import {useEffect,useRef,useState} from 'react';
import type {GameView} from '@/lib/game';
import {explore,flag,locationKey,locationSchema,loadWeather,searchLocations} from '@/services/location/location.service';
import {fallback,label,localClock,phase,season,temperatureBand,type Location,type World,type SharedWorld,type Weather} from '@/services/weather/weather.mapper';
import {publishWorld} from '@/game/weather/WeatherRuntime';
const newShared=():SharedWorld=>({inventory:{},collectedAt:0,questCount:0});
import {collect,buyDecoration,opportunity} from '@/game/weather/WeatherGameplay';
import {WeatherAudio} from '@/game/weather/WeatherAudio';
const read=(key:string,alt:any)=>{try{return JSON.parse(localStorage.getItem(key)||'null')||alt;}catch{return alt;}};
const save=(key:string,data:unknown)=>{try{localStorage.setItem(key,JSON.stringify(data));}catch{}};
const icon=(t:string)=>t.includes('snow')?'❄️':t==='thunderstorm'?'⛈️':t.includes('rain')?'🌧️':t==='fog'?'🌫️':t==='clear'?'☀️':t==='windy'?'🍃':'☁️';
type Props={state:GameView|null;now:number;onAction:(a:string,b?:Record<string,unknown>)=>Promise<unknown>};
export default function WorldPanel({state,now,onAction}:Props){
 const [privateWorld,setPrivateWorld]=useState<SharedWorld>(newShared),[loaded,setLoaded]=useState(false),[open,setOpen]=useState(false),[details,setDetails]=useState(false),[query,setQuery]=useState(''),[results,setResults]=useState<Location[]>([]),[recent,setRecent]=useState<Location[]>([]),[favorites,setFavorites]=useState<Location[]>([]),[candidate,setCandidate]=useState<Location|null>(null),[mode,setMode]=useState<'real'|'relaxed'>('real'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[searching,setSearching]=useState(false),[previews,setPreviews]=useState<Record<string,Weather>>({}),[sound,setSound]=useState(false);
 const seq=useRef(0),audio=useRef<WeatherAudio|null>(null),shared=state?.world,world=state?shared:privateWorld,w=world?.current,time=now||Date.now(),reward=opportunity(w,time);
 useEffect(()=>{const v=read('tap-world-v1',null);if(v?.current&&locationSchema.safeParse(v.current.location).success&&v.current.weather&&typeof v.inventory==='object'){setPrivateWorld(v);setMode(v.current.mode==='relaxed'?'relaxed':'real');}else setOpen(true);const valid=(v:any)=>Array.isArray(v)?v.filter(x=>locationSchema.safeParse(x).success).slice(0,20):[];setRecent(valid(read('tap-locations-recent',[])));setFavorites(valid(read('tap-locations-favorites',[])));setLoaded(true);return()=>audio.current?.dispose();},[]);
 useEffect(()=>{if(candidate)document.querySelector('.world-confirm[role=dialog]')?.scrollIntoView({behavior:'smooth',block:'center'});},[candidate]);
 useEffect(()=>{if(loaded)save('tap-world-v1',privateWorld);},[privateWorld,loaded]);
 useEffect(()=>{publishWorld(w,world?.decorations,time-Date.now());audio.current?.update(w,time);},[w,world?.decorations,time]);
 useEffect(()=>{if(state||!loaded||!privateWorld.current)return;let stop=false;const location=privateWorld.current.location;async function refresh(){try{const {weather}=await loadWeather(location);if(stop)return;setPrivateWorld(p=>!p.current||locationKey(p.current.location)!==locationKey(location)?p:{...p,current:{...p.current,weather:weather.fetchedAt===0&&p.current.weather.fetchedAt>0?{...p.current.weather,unavailable:true}:weather,changedAt:weather.type===p.current.weather.type?p.current.changedAt:Date.now()}});}catch{if(!stop)setPrivateWorld(p=>p.current?{...p,current:{...p.current,weather:{...p.current.weather,unavailable:true}}}:p);}}void refresh();const interval=setInterval(refresh,1200000);return()=>{stop=true;clearInterval(interval);};},[!!state,loaded,privateWorld.current?.location.selectedAt]);
 useEffect(()=>{if(!open)return;let stop=false;Promise.all(explore.map(async l=>{try{const d=await loadWeather(l);if(!stop)setPreviews(p=>({...p,[locationKey(l)]:d.weather}));}catch{}}));return()=>{stop=true;};},[open]);
 useEffect(()=>{const id=++seq.current;if(query.trim().length<2){setResults([]);setSearching(false);return;}setSearching(true);const timer=setTimeout(async()=>{try{const d=await searchLocations(query);if(id===seq.current){setResults(d.results);setError('');}}catch(e){if(id===seq.current)setError((e as Error).message);}finally{if(id===seq.current)setSearching(false);}},400);return()=>clearTimeout(timer);},[query]);
 function favorite(l:Location){const next=favorites.some(x=>locationKey(x)===locationKey(l))?favorites.filter(x=>locationKey(x)!==locationKey(l)):[l,...favorites].slice(0,20);setFavorites(next);save('tap-locations-favorites',next);}
 async function choose(){if(!candidate||busy)return;setBusy(true);setError('');try{const location={...candidate,selectedAt:Date.now()};if(state){const ok=await onAction('world_propose',{location,timeMode:mode});if(!ok)return;}else{let weather:Weather;try{weather=(await loadWeather(location)).weather;}catch{weather=fallback();}const at=Date.now();setPrivateWorld(p=>({...p,current:{location,weather,mode,startedAt:at,changedAt:at,seed:at%1000000}}));}const next=[location,...recent.filter(l=>locationKey(l)!==locationKey(location))].slice(0,8);setRecent(next);save('tap-locations-recent',next);setCandidate(null);setOpen(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function collectResource(){setError('');if(state){await onAction('world_collect');return;}try{const next=structuredClone(privateWorld);collect(next,time);setPrivateWorld(next);}catch(e){setError((e as Error).message);}}
 async function buy(name:string){if(state){await onAction('world_buy',{value:name});return;}try{const next=structuredClone(privateWorld);buyDecoration(next,name);setPrivateWorld(next);setError('');}catch(e){setError((e as Error).message);}}
 const card=(l:Location)=>{const weather=previews[locationKey(l)];return <div className="location-card" key={locationKey(l)}><button onClick={()=>{setCandidate(l);setMode(w?.mode||'real');}}><b>{flag(l.countryCode)} {l.city}</b><span>{l.region?l.region+', ':''}{l.country}</span><small>{localClock(l,time)}{weather?` · ${icon(weather.type)} ${weather.temperature===null?'—':Math.round(weather.temperature)+'°C'} · ${weather.unavailable?'Unavailable':label(weather.type)}`:''}</small></button><button aria-label={`Favourite ${l.city}`} aria-pressed={favorites.some(x=>locationKey(x)===locationKey(l))} onClick={()=>favorite(l)}>☆</button></div>;};
 return <section className="world-panel" aria-label="World location and weather">
  <div className="world-toolbar"><button onClick={()=>setDetails(!details)} className="weather-summary"><small>{state?'OUR WORLD · SHARED':'MY PRIVATE WORLD · SOLO'}</small><b>{w?`${flag(w.location.countryCode)} ${w.location.city}, ${w.location.country}`:'Choose your world location'}</b><span>{w?`${icon(w.weather.type)} ${w.weather.temperature===null?'—':Math.round(w.weather.temperature)+'°C'} · ${localClock(w.location,time)} · ${phase(w,time)}`:'Real places. Living weather.'}</span></button><button onClick={()=>setOpen(!open)}>⚙ World location</button><button aria-pressed={sound} onClick={()=>{if(!audio.current)audio.current=new WeatherAudio();audio.current.setEnabled(!sound);setSound(!sound);}}>Sound {sound?'on':'off'}</button></div>
  {w?.weather.unavailable&&<p role="status">Live weather temporarily unavailable. {w.weather.fetchedAt?'Using the last known weather.':'Using partly cloudy conditions until live weather returns.'}</p>}
  {details&&w&&<div className="weather-details"><span>{label(w.weather.type)} · Feels like {w.weather.feelsLike??'—'}°C</span><span>Wind {w.weather.wind} km/h · Humidity {w.weather.humidity??'—'}%</span><span>{temperatureBand(w.weather.temperature)} · {season(w.location,time)} · {w.mode==='real'?'Real location time':'Relaxed game time'}</span><span>Sunrise {w.weather.sunrise?localClock(w.location,w.weather.sunrise):'Unavailable'} · Sunset {w.weather.sunset?localClock(w.location,w.weather.sunset):'Unavailable'}</span><span>Weather updated {w.weather.fetchedAt?Math.max(0,Math.floor((time-w.weather.fetchedAt)/60000))+' min ago':'not yet'}</span><a href={w.weather.provider==='MET Norway'?'https://www.met.no/':'https://open-meteo.com/'} target="_blank" rel="noreferrer">Weather: {w.weather.provider} · Locations: GeoNames</a></div>}
  {shared?.proposal&&time-shared.proposal.at<300000&&<div className="world-confirm" role="status"><h3>{state?.players[shared.proposal.by]?.name} wants to change Our World</h3><p>{shared.proposal.location.city}, {shared.proposal.location.country} · {shared.proposal.mode==='real'?'Real location time':'Relaxed game time'}</p>{shared.proposal.by!==state?.me&&<button onClick={()=>onAction('world_accept',{proposalId:shared.proposal!.id})}>Accept</button>}<button onClick={()=>onAction('world_decline',{proposalId:shared.proposal!.id})}>{shared.proposal.by===state?.me?'Cancel request':'Decline'}</button></div>}
  {open&&<div className="world-picker"><h2>{state?'Choose Our World location':'Choose your world location'}</h2><p>Search a city or country. Pick the correct region. No GPS needed.</p><label htmlFor="world-search">Search locations</label><input id="world-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Colombo, Sri Lanka" autoComplete="off"/>{searching&&<p role="status">Searching…</p>}{query.length>=2&&!searching&&!results.length&&<p>No results? Try the city name alone or a suggested city below.</p>}<div className="location-grid">{results.map(card)}</div>{favorites.length>0&&<><h3>Favourite places</h3><div className="location-grid">{favorites.map(card)}</div></>}{recent.length>0&&<><h3>Recent places</h3><div className="location-grid">{recent.map(card)}</div></>}<h3>Explore the world</h3><div className="location-grid">{explore.map(card)}</div><button onClick={()=>setOpen(false)}>Continue playing</button></div>}
  {candidate&&<div className="world-confirm" role="dialog" aria-modal="false" aria-label="Change world location"><h3>Change {state?'Our World':'world'} location?</h3><p>Your weather, time and environment will change to match <b>{candidate.city}, {candidate.country}</b>. Your progress, plants and decorations stay saved.</p><label>World time <select value={mode} onChange={e=>setMode(e.target.value as 'real'|'relaxed')}><option value="real">Real location time (recommended)</option><option value="relaxed">Relaxed game time</option></select></label><button disabled={busy} onClick={choose}>{busy?'Loading weather…':state&&state.players.length===2?'Ask partner to change':'Change'}</button><button disabled={busy} onClick={()=>setCandidate(null)}>Cancel</button></div>}
  {w&&<details className="world-journal"><summary>✦ Weather quest · {reward.quest} · {(world?.inventory[reward.token]||0)%5}/5</summary><p>{reward.merchant} is visiting. Look for {reward.fish} every third successful cast. Rain speeds up new plants.</p><button disabled={time-(world?.collectedAt||0)<15000} onClick={collectResource}>{time-(world?.collectedAt||0)<15000?`Resource forms in ${Math.ceil((15000-time+(world?.collectedAt||0))/1000)}s`:`Collect ${reward.token}`}</button><p>Inventory: {Object.entries(world?.inventory||{}).map(([k,v])=>`${k}: ${v}`).join(' · ')||'Start collecting'}</p><p>Every 5 resources earns 1 Explorer Star. Spend stars on lasting world decorations.</p>{['Lantern','Flower arch','Snow globe'].map(name=><button key={name} disabled={world?.decorations?.includes(name)} onClick={()=>buy(name)}>{world?.decorations?.includes(name)?'✓ ':''}{name} · 1 star</button>)}</details>}
  {error&&<p className="error" role="alert">{error}</p>}
 </section>;
}
