import {type GameWeather,type Weather} from './weather.mapper';
// Provider-specific WMO codes are confined to this adapter.
export function mapWmo(code:number,wind=0):GameWeather{if(code>=95)return 'thunderstorm';if([75,86].includes(code))return 'heavy_snow';if([73,85].includes(code))return 'snow';if([71,77].includes(code))return 'light_snow';if([65,67,82].includes(code))return 'heavy_rain';if([63,66,81].includes(code))return 'rain';if([51,53,55,56,57,61,80].includes(code))return 'light_rain';if([45,48].includes(code))return 'fog';if(wind>=30)return 'windy';return code===0?'clear':code===1||code===2?'partly_cloudy':'cloudy';}
export class WeatherAdapter{
 static normalize(data:any,now:number):Weather{const c=data?.current;if(!c||!Number.isFinite(c.weather_code)||!Number.isFinite(c.temperature_2m)||!Number.isFinite(c.wind_speed_10m))throw Error('Incomplete weather response');return {type:mapWmo(c.weather_code,c.wind_speed_10m),temperature:c.temperature_2m,feelsLike:Number.isFinite(c.apparent_temperature)?c.apparent_temperature:null,humidity:Number.isFinite(c.relative_humidity_2m)?c.relative_humidity_2m:null,wind:c.wind_speed_10m,sunrise:data.daily?.sunrise?.[0]?data.daily.sunrise[0]*1000:null,sunset:data.daily?.sunset?.[0]?data.daily.sunset[0]*1000:null,isDay:!!c.is_day,fetchedAt:now,expiresAt:now+1200000,unavailable:false,provider:'Open-Meteo',rawCode:c.weather_code};}
 static async primary(latitude:number,longitude:number,timezone:string):Promise<Weather>{const q=new URLSearchParams({latitude:String(latitude),longitude:String(longitude),timezone,current:'temperature_2m,apparent_temperature,relative_humidity_2m,is_day,weather_code,wind_speed_10m',daily:'sunrise,sunset',timeformat:'unixtime',forecast_days:'1'});const r=await fetch('https://api.open-meteo.com/v1/forecast?'+q,{signal:AbortSignal.timeout(5500)});if(!r.ok)throw Error('Weather provider HTTP '+r.status+': '+(await r.text()).slice(0,160));return this.normalize(await r.json(),Date.now());}
 static async fetch(latitude:number,longitude:number,timezone:string):Promise<Weather>{try{return await this.primary(latitude,longitude,timezone);}catch(error){console.warn('Primary weather provider unavailable:',(error as Error).message);return this.met(latitude,longitude,timezone);}}
 static async met(latitude:number,longitude:number,timezone:string):Promise<Weather>{
  const now=Date.now(),date=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(now),offset=new Intl.DateTimeFormat('en',{timeZone:timezone,timeZoneName:'longOffset'}).formatToParts(now).find(p=>p.type==='timeZoneName')!.value.replace('GMT','')||'+00:00';
  const q=new URLSearchParams({lat:latitude.toFixed(4),lon:longitude.toFixed(4)}),sunq=new URLSearchParams({...Object.fromEntries(q),date,offset});
  const get=async(url:string)=>{const r=await fetch(url,{headers:{'User-Agent':'TapTogether/1.0 https://github.com/ceylonroameryt-bit/Tap-Together'},signal:AbortSignal.timeout(6000)});if(!r.ok)throw Error('MET Norway HTTP '+r.status);return r.json() as Promise<any>;};
  const [data,sun]=await Promise.all([get('https://api.met.no/weatherapi/locationforecast/2.0/compact?'+q),get('https://api.met.no/weatherapi/sunrise/3.0/sun?'+sunq).catch(()=>null)]);
  const entries=data?.properties?.timeseries;if(!Array.isArray(entries)||!entries.length)throw Error('Incomplete MET weather response');const row=entries.reduce((best:any,e:any)=>Math.abs(Date.parse(e.time)-now)<Math.abs(Date.parse(best.time)-now)?e:best,entries[0]);if(Math.abs(Date.parse(row.time)-now)>10800000)throw Error('MET weather is stale');
  const c=row.data.instant.details,code=String(row.data.next_1_hours?.summary?.symbol_code||row.data.next_6_hours?.summary?.symbol_code||'cloudy'),wind=c.wind_speed*3.6;if(!Number.isFinite(c.air_temperature)||!Number.isFinite(wind))throw Error('Incomplete MET weather values');
  const type:GameWeather=code.includes('thunder')?'thunderstorm':code.includes('snow')||code.includes('sleet')?(code.includes('heavy')?'heavy_snow':code.includes('light')?'light_snow':'snow'):code.includes('rain')?(code.includes('heavy')?'heavy_rain':code.includes('light')?'light_rain':'rain'):code.includes('fog')?'fog':wind>=30?'windy':code.includes('clearsky')?'clear':code.includes('fair')||code.includes('partlycloudy')?'partly_cloudy':'cloudy';
  const sunrise=sun?.properties?.sunrise?.time?Date.parse(sun.properties.sunrise.time):null,sunset=sun?.properties?.sunset?.time?Date.parse(sun.properties.sunset.time):null;
  return {type,temperature:c.air_temperature,feelsLike:null,humidity:c.relative_humidity??null,wind:Math.round(wind*10)/10,sunrise,sunset,isDay:sunrise&&sunset?now>=sunrise&&now<sunset:code.includes('_day'),fetchedAt:now,expiresAt:now+1200000,unavailable:false,provider:'MET Norway',rawCode:null};
 }

}
