import * as THREE from 'three';
import {activeWorld,activeDecorations,worldNow} from './WeatherRuntime';
import {WeatherController} from './WeatherController';
import {WeatherParticles} from './WeatherParticles';
import {season} from '@/services/weather/weather.mapper';
export function installWeather(renderer:THREE.WebGLRenderer,scene:THREE.Scene,camera:THREE.Camera){
 const groundMaterials=new Map<THREE.MeshStandardMaterial,{color:THREE.Color,roughness:number}>();scene.traverse(o=>{if(o instanceof THREE.Mesh&&o.position.y<.25&&o.material instanceof THREE.MeshStandardMaterial)groundMaterials.set(o.material,{color:o.material.color.clone(),roughness:o.material.roughness});});
 const controller=new WeatherController(),particles=new WeatherParticles(scene),group=new THREE.Group();scene.add(group);const resources:{dispose:()=>void}[]=[];const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const material=(color:string,extra:THREE.MeshStandardMaterialParameters={})=>{const m=new THREE.MeshStandardMaterial({color,...extra});resources.push(m);return m;};
 function mesh(geo:THREE.BufferGeometry,mat:THREE.Material,parent:THREE.Object3D,x=0,y=0,z=0){resources.push(geo);const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);parent.add(m);return m;}
 const cloudMat=material('#f0f4f8',{transparent:true,opacity:.4}),white=material('#eef7ff'),green=material('#74ba86'),gold=material('#ffde84'),pink=material('#f69ebf'),wood=material('#896c5e');
 const clouds:THREE.Group[]=[];for(let i=0;i<5;i++){const cloud=new THREE.Group();group.add(cloud);cloud.position.set(i*4-8,7+(i%2),-5);for(let j=0;j<3;j++){const m=mesh(new THREE.SphereGeometry(1,12,8),cloudMat,cloud,j*.85,0,0);m.scale.set(1.2,.45,.65);}clouds.push(cloud);}
 const puddles:THREE.Mesh[]=[];const wet=material('#8aaac1',{transparent:true,opacity:0,metalness:.5,roughness:.05});for(let i=0;i<6;i++){const p=mesh(new THREE.CircleGeometry(.6,24),wet,group,(i%3)*3-4,.14,Math.floor(i/3)*6-3);p.rotation.x=-Math.PI/2;p.scale.y=.6;puddles.push(p);}
 const snow=material('#edf5ff',{transparent:true,opacity:0});const caps:THREE.Mesh[]=[];for(let i=0;i<12;i++){const c=mesh(new THREE.SphereGeometry(.8,12,8),snow,group,Math.sin(i*3)*7,.04,Math.cos(i*3)*6);c.scale.y=.08;caps.push(c);}
 const trees:THREE.Group[]=[];for(let i=0;i<4;i++){const tree=new THREE.Group();group.add(tree);tree.position.set(i%2?7:-7,0,i<2?-4:3);mesh(new THREE.CylinderGeometry(.07,.12,1.4,7),wood,tree,0,.7);mesh(new THREE.ConeGeometry(.65,1.7,8),green,tree,0,1.8);trees.push(tree);}
 const critters:THREE.Group[]=[];for(let i=0;i<10;i++){const g=new THREE.Group();group.add(g);const left=mesh(new THREE.SphereGeometry(.13,8,6),i%2?gold:pink,g,-.12,0);left.scale.z=.25;const right=mesh(new THREE.SphereGeometry(.13,8,6),i%2?gold:pink,g,.12,0);right.scale.z=.25;critters.push(g);}
 const npc=new THREE.Group();group.add(npc);npc.position.set(5.5,0,-1);const coat=material('#c4a4ed');mesh(new THREE.CylinderGeometry(.25,.4,.8,10),coat,npc,0,.5);mesh(new THREE.SphereGeometry(.3,12,10),green,npc,0,1.05);for(const x of [-.14,.14])mesh(new THREE.SphereGeometry(.05,8,6),white,npc,x,1.12,.25);
 const umbrella=new THREE.Group();npc.add(umbrella);mesh(new THREE.CylinderGeometry(.025,.025,1.8,6),wood,umbrella,.4,1);mesh(new THREE.ConeGeometry(.85,.3,12),pink,umbrella,.4,1.9);
 const scarf=mesh(new THREE.TorusGeometry(.27,.07,6,16),pink,npc,0,.83);scarf.rotation.x=Math.PI/2;const fan=mesh(new THREE.CircleGeometry(.22,8),gold,npc,.45,.65,.1);
 const rainFrog=new THREE.Group();group.add(rainFrog);rainFrog.position.set(-4,.25,3);mesh(new THREE.SphereGeometry(.24,10,8),green,rainFrog);for(const x of [-.12,.12])mesh(new THREE.SphereGeometry(.08,8,6),white,rainFrog,x,.2,.1);
 const leaves:THREE.Mesh[]=[];for(let i=0;i<12;i++){const l=mesh(new THREE.PlaneGeometry(.18,.1),material('#c59b57',{side:THREE.DoubleSide}),group);leaves.push(l);}
 const shelter=new THREE.Group();group.add(shelter);shelter.position.set(6.5,0,-4);mesh(new THREE.ConeGeometry(1.1,.65,4),wood,shelter,0,2.1);for(const x of [-.7,.7])mesh(new THREE.CylinderGeometry(.05,.05,1.8,6),wood,shelter,x,.9);
 const token=mesh(new THREE.OctahedronGeometry(.22),gold,group,-5,1,1);const lantern=new THREE.Group();group.add(lantern);lantern.position.set(-5,0,-3);mesh(new THREE.CylinderGeometry(.035,.05,1.8,6),wood,lantern,0,.9);mesh(new THREE.BoxGeometry(.3,.45,.3),gold,lantern,0,1.8);const lamp=new THREE.PointLight('#ffd792',0,7);lamp.position.set(-5,1.8,-3);group.add(lamp);
 const arch=new THREE.Group();group.add(arch);arch.position.set(-5,0,4);mesh(new THREE.TorusGeometry(.8,.12,8,24,Math.PI),pink,arch,0,1);for(const x of [-.8,.8])mesh(new THREE.CylinderGeometry(.1,.1,1,6),green,arch,x,.5);
 const globe=mesh(new THREE.SphereGeometry(.45,16,12),material('#bbdfff',{transparent:true,opacity:.65}),group,5,.5,4);
 const tracks:THREE.Mesh[]=[];for(let i=0;i<8;i++){const m=mesh(new THREE.CircleGeometry(.09,8),material('#abbacb',{transparent:true,opacity:.4}),group,5.5+(i%2)*.18,.16,-1-i*.35);m.rotation.x=-Math.PI/2;tracks.push(m);}
 const footprints:THREE.Mesh[]=[];const footprintMat=material('#a9bac9',{transparent:true,opacity:.4});for(let i=0;i<20;i++){const f=mesh(new THREE.CircleGeometry(.12,8),footprintMat,group);f.rotation.x=-Math.PI/2;f.visible=false;footprints.push(f);}const previousPositions=new Map<number,THREE.Vector3>();let footprintIndex=0;
 const lightning=mesh(new THREE.CylinderGeometry(.025,.055,4,5),material('#d4d5ff',{emissive:'#8888bb',emissiveIntensity:.6,transparent:true,opacity:0}),group,-4,5,-6);lightning.rotation.z=.25;
 const oldRender=renderer.render.bind(renderer);let last=performance.now();const sky=new THREE.Color();
 renderer.render=((s:THREE.Scene,c:THREE.Camera)=>{const w=activeWorld();if(w){const now=worldNow(),v=controller.update(w,now),dt=Math.min(.06,(performance.now()-last)/1000);last=performance.now();const t=reduced?0:now/1000;
 sky.set('#a9dff5').lerp(new THREE.Color('#8d9caa'),v.cloud*.7).lerp(new THREE.Color('#16233f'),v.night);renderer.setClearColor(sky);scene.background=sky;scene.fog=new THREE.Fog(sky,Math.max(4,35-v.fog*30),Math.max(20,110-v.fog*85));
 scene.traverse(o=>{if(o instanceof THREE.DirectionalLight)o.intensity=(3-v.cloud*1.8)*(1-v.night*.85);if(o instanceof THREE.HemisphereLight)o.intensity=(2.5-v.cloud*.7)*(1-v.night*.65);});
 cloudMat.opacity=.15+v.cloud*.65;cloudMat.color.set('#edf2f7').lerp(new THREE.Color('#424c64'),v.cloud*.7+v.night*.2);clouds.forEach((g,i)=>{g.position.x=((t*(.08+v.wind*.35)+i*4)%24)-12;});
 const flash=w.weather.type==='thunderstorm'&&!reduced?Math.max(0,1-((now-w.changedAt)%24000)/700):0;(lightning.material as THREE.MeshStandardMaterial).opacity=flash*.7;
 scene.traverse(o=>{if(!o.userData.weatherCharacter)return;const pos=o.getWorldPosition(new THREE.Vector3()),old=previousPositions.get(o.id);if(old&&pos.distanceTo(old)>.4){const f=footprints[footprintIndex++%footprints.length];f.position.set(pos.x,.18,pos.z);f.visible=v.snow>.2;previousPositions.set(o.id,pos);}else if(!old)previousPositions.set(o.id,pos);});if(v.snow<.1)footprints.forEach(f=>f.visible=false);
 groundMaterials.forEach((base,m)=>{m.roughness=base.roughness*(1-v.rain*.85);m.color.copy(base.color).lerp(new THREE.Color('#eff6ff'),v.snow*.75);});scarf.visible=v.cold>.5;fan.visible=v.hot>.5;fan.rotation.z=Math.sin(t*4)*.4;rainFrog.visible=v.rain>.2;rainFrog.position.y=.25+Math.max(0,Math.sin(t*2))*.2;leaves.forEach((l,i)=>{l.visible=v.wind>.25;l.position.set(((t*(1+v.wind)+i*2)%18)-9,1+(i%4)*.4,Math.sin(t+i)*5);l.rotation.set(t+i,t*.5,0);});gold.emissive.set('#8a7333');gold.emissiveIntensity=v.night*.8;
 particles.update(dt,v.rain,v.snow,v.wind,reduced);wet.opacity=v.rain*.55;snow.opacity=v.snow*.85;trees.forEach((g,i)=>g.rotation.z=Math.sin(t*2+i)*(.02+v.wind*.12));const autumn=season(w.location,now)==='Autumn';green.color.set(autumn?'#c39759':season(w.location,now)==='Winter'?'#8da7a2':'#74ba86');
 critters.forEach((g,i)=>{g.visible=v.rain<.2&&v.snow<.2;g.position.set(Math.sin(t*.4+i)*6,1.5+Math.sin(t+i)*.5,Math.cos(t*.3+i)*5);g.scale.setScalar(v.night>.5?.35:1);g.children.forEach((o,j)=>o.rotation.y=Math.sin(t*8)*.6*(j?1:-1));});
 umbrella.visible=v.rain>.15;npc.position.x=5.5+v.rain*.7;npc.position.z=-1-v.rain*2.5;npc.rotation.z=v.cold>.5?Math.sin(t*15)*.015:v.hot>.5?Math.sin(t*2)*.05:Math.sin(t)*.015;coat.color.set(v.cold>.5?'#698ac7':v.hot>.5?'#ffe8ae':'#c4a4ed');tracks.forEach(m=>m.visible=v.snow>.2);
 token.rotation.y=t;token.position.y=1+Math.sin(t*2)*.15;gold.color.set(w.weather.type==='thunderstorm'?'#c19bff':v.snow>.1?'#d7f5ff':v.rain>.1?'#86daff':v.night>.5?'#c3bdff':'#ffde84');const owned=activeDecorations();lantern.visible=owned.includes('Lantern');lamp.intensity=lantern.visible?v.night*4:0;arch.visible=owned.includes('Flower arch');globe.visible=owned.includes('Snow globe');
 }else{group.visible=false;particles.points.visible=false;}if(w){group.visible=true;particles.points.visible=true;}oldRender(s,c);}) as typeof renderer.render;
 return()=>{renderer.render=oldRender;group.removeFromParent();particles.dispose();resources.forEach(r=>r.dispose());};
}
