import {z} from 'zod';
import type {Location,World} from '../weather/weather.mapper';
export const locationSchema=z.object({country:z.string().min(1).max(100),countryCode:z.string().regex(/^[A-Z]{2}$/),city:z.string().min(1).max(100),region:z.string().max(100).optional(),latitude:z.number().min(-90).max(90),longitude:z.number().min(-180).max(180),timezone:z.string().max(100).refine(s=>{try{new Intl.DateTimeFormat('en',{timeZone:s});return true;}catch{return false;}}),selectedAt:z.number().optional().default(0)});
export const flag=(code:string)=>/^[A-Z]{2}$/.test(code)?String.fromCodePoint(...[...code].map(c=>127397+c.charCodeAt(0))):'🌍';
export const locationKey=(l:Location)=>`${l.latitude.toFixed(3)},${l.longitude.toFixed(3)}`;
export const explore:Location[]=[['London','United Kingdom','GB',51.5085,-.1257,'Europe/London'],['Colombo','Sri Lanka','LK',6.9319,79.8478,'Asia/Colombo'],['Tokyo','Japan','JP',35.6895,139.6917,'Asia/Tokyo'],['New York','United States','US',40.7143,-74.006,'America/New_York'],['Toronto','Canada','CA',43.7001,-79.4163,'America/Toronto'],['Sydney','Australia','AU',-33.8679,151.2073,'Australia/Sydney'],['Paris','France','FR',48.8534,2.3488,'Europe/Paris'],['Reykjavík','Iceland','IS',64.1355,-21.8954,'Atlantic/Reykjavik'],['Dubai','United Arab Emirates','AE',25.0657,55.1713,'Asia/Dubai']].map(([city,country,countryCode,latitude,longitude,timezone])=>({city,country,countryCode,latitude,longitude,timezone,selectedAt:0} as Location));
export async function worldRequest(body:unknown){const r=await fetch('/api/world',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(18000)});const d=await r.json() as any;if(!r.ok)throw Error(d.error||'World service unavailable');return d;}
export const loadWeather=async(location:Location)=>worldRequest({action:'weather',location}) as Promise<{weather:World['weather']}>;
export const searchLocations=async(query:string)=>worldRequest({action:'search',query}) as Promise<{results:Location[]}>;
