'use client';
import {installWeather} from '@/game/weather/WeatherEffects';
import {activeWorld} from '@/game/weather/WeatherRuntime';
import {isRain,phase} from '@/services/weather/weather.mapper';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {newAngler,fishMove,fishTypes,type Angler} from '@/lib/fishing';
import type {GameView} from '@/lib/game';
type Props={state:GameView|null;now:number;busy:boolean;onAction:(a:string,b?:Record<string,unknown>)=>Promise<unknown>};
export default function FishingPond({state,now,busy,onAction}:Props){
 const mount=useRef<HTMLDivElement>(null),[solo,setSolo]=useState<Angler>(()=>newAngler()),[end,setEnd]=useState(0),[fault,setFault]=useState(''),[error,setError]=useState('');
 const p=state?.anglers?.[state.me]||solo,time=now||Date.now(),active=state?!!state.start&&!state.finished&&time>=state.start:!!end&&time<end&&solo.catches<6,biting=!!p.biteAt&&time>=p.biteAt&&time<=p.closesAt,line=!!p.biteAt&&time<=p.closesAt,live=useRef({p,biting,line});live.current={p,biting,line};
 function move(value:string){if(!active||busy)return;setError('');if(state){void onAction('fish',{value});return;}try{const n=structuredClone(solo);fishMove(n,value,Date.now(),activeWorld());setSolo(n);}catch(e){setError((e as Error).message);}}
 const command=useRef(move);command.current=move;
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.code!=='Space'||e.repeat||e.target instanceof HTMLInputElement||e.target instanceof HTMLButtonElement||e.target instanceof HTMLSelectElement||e.target instanceof HTMLTextAreaElement)return;e.preventDefault();command.current(live.current.line?'reel':'cast');};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{const el=mount.current;if(!el)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'low-power'});}catch{setFault('3D is unavailable. The bite meter and controls below still work.');return;}renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor('#233d68');el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Animated moonlit fishing pond');
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(43,1,.1,100);const geos:THREE.BufferGeometry[]=[],mats:THREE.Material[]=[];const mat=(c:string)=>{const m=new THREE.MeshStandardMaterial({color:c,roughness:.4});mats.push(m);return m;};const blue=mat('#518db8'),mint=mat('#78d6ab'),cream=mat('#fff4d5'),gold=mat('#ffd174'),wood=mat('#ac7e68'),pink=mat('#e496ca');
 const mesh=(g:THREE.BufferGeometry,m:THREE.Material,parent:THREE.Object3D,x=0,y=0,z=0)=>{geos.push(g);const o=new THREE.Mesh(g,m);o.position.set(x,y,z);parent.add(o);return o;};const ball=(m:THREE.Material,parent:THREE.Object3D,x:number,y:number,z:number,size:number)=>mesh(new THREE.SphereGeometry(size,20,16),m,parent,x,y,z);
 scene.add(new THREE.HemisphereLight(0xdbedff,0x465281,3));const light=new THREE.DirectionalLight(0xffedc7,3);light.position.set(-5,10,6);scene.add(light);
 mesh(new THREE.CylinderGeometry(5.8,5.2,.65,64),mat('#556f8d'),scene,0,-.6);mesh(new THREE.CylinderGeometry(5.65,5.65,.12,64),blue,scene,0,-.2);for(let i=0;i<6;i++)mesh(new THREE.BoxGeometry(.75,.18,3.7),wood,scene,(i-2.5)*.78,.02,3.2);
 const frog=new THREE.Group();frog.position.set(-.9,.2,2.7);scene.add(frog);const body=ball(mint,frog,0,.55,0,.6);body.scale.set(1,.8,.85);const belly=ball(cream,frog,0,.48,-.32,.4);belly.scale.z=.3;for(const x of [-.35,.35]){ball(mint,frog,x,1,-.2,.26);ball(cream,frog,x,1,-.39,.17);ball(mat('#273e55'),frog,x,1,-.53,.08);const foot=ball(mint,frog,x*1.5,.08,-.1,.3);foot.scale.y=.4;}mesh(new THREE.ConeGeometry(.7,.55,20),gold,frog,0,1.42);
 const rod=mesh(new THREE.CylinderGeometry(.045,.065,3.7,8),wood,scene,-.45,1.1,1.45);rod.rotation.x=-.8;const fishingLine=mesh(new THREE.CylinderGeometry(.012,.012,1.1,6),cream,scene,0,.52,-.1);const bobber=ball(pink,scene,0,.02,-.1,.17);
 const rings:THREE.Mesh[]=[];for(let i=0;i<3;i++){const ring=mesh(new THREE.TorusGeometry(.4,.018,6,50),cream,scene,0,-.1,-.1);ring.rotation.x=-Math.PI/2;rings.push(ring);}
 const fishes:THREE.Group[]=[];for(let i=0;i<5;i++){const f=new THREE.Group();scene.add(f);const material=mat(fishTypes[i%3].color);const b=ball(material,f,0,0,0,.3);b.scale.set(1.6,.55,1);const tail=mesh(new THREE.ConeGeometry(.23,.4,3),material,f,-.5,0,0);tail.rotation.z=Math.PI/2;fishes.push(f);}
 for(let i=0;i<7;i++){const a=i*2.4;mesh(new THREE.CylinderGeometry(.45,.45,.04,20),mint,scene,Math.cos(a)*4,-.09,Math.sin(a)*3);}
 const moon=ball(cream,scene,-3,4,-3,.65);const glow=new THREE.PointLight(0xbce9ff,8,15);glow.position.copy(moon.position);scene.add(glow);
 const resize=()=>{renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.position.set(7,9,10).multiplyScalar(Math.max(1,.9/camera.aspect));camera.lookAt(0,.3,0);camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(el);resize();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let frame=0;
 const disposeWeather=installWeather(renderer,scene,camera);const draw=(t:number)=>{frame=requestAnimationFrame(draw);if(document.hidden)return;const v=live.current;const world=activeWorld();moon.visible=!world||phase(world,Date.now())==='night';glow.intensity=moon.visible?8:0;bobber.visible=fishingLine.visible=v.line;bobber.position.y=v.biting?Math.sin(t*.02)*.13:.02;bobber.scale.setScalar(v.biting?1.4:1);rings.forEach((r,i)=>{r.visible=v.line;const scale=reduced?1:1+(t*.001+i*.7)%2;r.scale.setScalar(scale);});fishes.forEach((f,i)=>{const a=(reduced?0:t*.00025)+i*1.25;f.position.set(Math.cos(a)*(2+i*.3),-.13,Math.sin(a)*(1.5+i*.3)-.5);f.rotation.y=-a;});frog.rotation.z=reduced?0:Math.sin(t*.0015)*.025;renderer.render(scene,camera);};frame=requestAnimationFrame(draw);const lost=(e:Event)=>{e.preventDefault();setFault('3D paused. Keep playing with the bite meter below.');};renderer.domElement.addEventListener('webglcontextlost',lost);
 return()=>{cancelAnimationFrame(frame);observer.disconnect();renderer.domElement.removeEventListener('webglcontextlost',lost);geos.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());disposeWeather();renderer.dispose();renderer.domElement.remove();};},[]);
 const finishedSolo=!!end&&!active;
 return <div className="fishing-game"><div className="fishing-heading"><span>{state?'TWO-PLAYER FISHING DUEL':'SOLO POND CHALLENGE'}</span><span>{state?'First to 6 fish':end?`${Math.max(0,Math.ceil((end-time)/1000))}s left`:'90 seconds · 6 catches'}</span></div><div className="fishing-scene" ref={mount}/><div className="fishing-stats"><b>🐟 {p.catches}/6</b><b>✦ {p.points} pond points</b><b>🔥 {p.combo} combo</b></div>{state?.anglers&&<p className="hint">{state.players[1-state.me]?.name||'Partner'}: {state.anglers[1-state.me].catches} fish · {state.anglers[1-state.me].points} pond points</p>}
 <div className={`bite-meter ${biting?'bite-now':''}`} role="status" aria-live="polite">{!active?finishedSolo?solo.catches>=6?'Pond mastered! Six fish caught.':'Round complete. Try for six next time.':'Ready for a little fishing?':biting?'BITE! REEL NOW!':line?'Watch the float… wait for green':p.biteAt?'Fish escaped. Cast again.':'Cast your line'}</div><div className="fishing-actions">{!state&&(!end||finishedSolo)?<button className="primary" onClick={()=>{setSolo(newAngler());setEnd(Date.now()+90000);setError('');}}>{end?'Play again':'Start solo fishing'}</button>:<><button disabled={!active||busy||line} onClick={()=>move('cast')}>🎣 Cast</button><button className={biting?'reel-ready':''} disabled={!active||busy||!p.biteAt} onClick={()=>move('reel')}>Reel in</button></>}</div><p className="hint">{p.last}</p><div className="fish-collection">{fishTypes.map(f=><span key={f.name} className={p.collection.includes(f.name)?'caught':''}>{p.collection.includes(f.name)?'✓':'◇'} {f.name}</span>)}</div><p className="hint">Watch for green, then reel! Catch streaks narrow the bite window and earn bonus points. Keyboard: Space to cast or reel.</p>{(fault||error)&&<p className="error" role="alert">{error||fault}</p>}</div>;
}
