'use client';
import {installWeather} from '@/game/weather/WeatherEffects';
import {activeWorld} from '@/game/weather/WeatherRuntime';
import {isRain,phase} from '@/services/weather/weather.mapper';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {newGarden,gardenMove,restoreGarden,seeds,type Garden} from '@/lib/garden';
import {villagePlaces,villageCell,villagePoint,villageSpawn,villagePath,walkable} from '@/lib/village';
import type {GameView} from '@/lib/game';
type Props={state:GameView|null;now:number;busy:boolean;onAction:(a:string,b?:Record<string,unknown>)=>Promise<unknown>};
export default function FrogGarden({state,now,busy,onAction}:Props){
 const host=useRef<HTMLDivElement>(null),[solo,setSolo]=useState<Garden>(()=>newGarden()),[loaded,setLoaded]=useState(false),[cell,setCell]=useState(12),[seed,setSeed]=useState('daisy'),[error,setError]=useState(''),[fault,setFault]=useState(''),[view,setView]=useState(false),[place,setPlace]=useState<(typeof villagePlaces)[number]>(villagePlaces[0]);
 const garden=state?.garden||solo,clock=state?now:Date.now(),canPlay=!state||!!state.start&&!state.finished&&now>=state.start,current=useRef({garden,cell,clock,view,me:state?.me||0});current.current={garden,cell,clock,view,me:state?.me||0};
 useEffect(()=>{try{const raw=localStorage.getItem('tap-frog-garden-v1');if(raw){const g=restoreGarden(JSON.parse(raw));if(g)setSolo(g);else setError('The saved garden could not be read. A fresh garden is ready.');}}catch{}setLoaded(true);},[]);
 useEffect(()=>{if(!loaded)return;try{localStorage.setItem('tap-frog-garden-v1',JSON.stringify(solo));}catch{setError('Device storage is unavailable. Keep this tab open to keep your solo garden.');}},[solo,loaded]);
 useEffect(()=>{if(state)return;const t=setInterval(()=>setSolo(g=>{const w=activeWorld();const weather=w?(isRain(w.weather.type)?'rain':phase(w,Date.now())==='night'?'night':'sun'):'sun';return g.weather===weather?g:{...g,weather};}),1000);return()=>clearInterval(t);},[!!state]);
 function explore(verb:string,destination:number,landmark=''){if(busy)return;if(state){void onAction('garden',{value:verb,cell:destination,choice:landmark});return;}try{const next=structuredClone(solo);gardenMove(next,0,verb,destination,landmark,Date.now(),activeWorld());setSolo(next);setError('');}catch(e){setError((e as Error).message);}}
 const walkRef=useRef(explore);walkRef.current=explore;
 function goTo(p:(typeof villagePlaces)[number]){setPlace(p);explore('walk',villageCell(p.x,p.z));}
 function move(verb:string){if(!canPlay||busy)return;setError('');if(state){void onAction('garden',{value:verb,cell,choice:seed});return;}try{const next=structuredClone(solo);gardenMove(next,0,verb,cell,seed,Date.now(),activeWorld());setSolo(next);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{
  const el=host.current;if(!el)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'low-power'});}catch{setFault('3D is unavailable here. Your garden still works using the plot buttons below.');return;}
  renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Lilybrook village. Tap the ground to walk. Tap a flower bed to garden.');
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(40,1,.1,100),resources:{dispose:()=>void}[]=[],targets:THREE.Object3D[]=[],beds:THREE.Mesh[]=[],plants:THREE.Group[]=[],frogs:THREE.Group[]=[];
  const material=(color:string,extra:THREE.MeshStandardMaterialParameters={})=>{const m=new THREE.MeshStandardMaterial({color,roughness:.6,...extra});resources.push(m);return m;};
  const grass=material('#8dcba1'),soil=material('#71514c'),leaf=material('#349766'),water=material('#69cee0',{metalness:.25,roughness:.2}),cream=material('#fff5dc'),wood=material('#ad795f'),pink=material('#ff85b9'),yellow=material('#ffe08a');
  function mesh(geo:THREE.BufferGeometry,mat:THREE.Material,parent:THREE.Object3D,x=0,y=0,z=0){resources.push(geo);const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
  function ball(parent:THREE.Object3D,mat:THREE.Material,x:number,y:number,z:number,sx:number,sy=sx,sz=sx){const b=mesh(new THREE.SphereGeometry(1,16,12),mat,parent,x,y,z);b.scale.set(sx,sy,sz);return b;}
  const ambient=new THREE.HemisphereLight(0xffffff,0x618185,2.5);scene.add(ambient);const sun=new THREE.DirectionalLight(0xffedd0,3);sun.position.set(-4,12,7);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-18;sun.shadow.camera.right=18;sun.shadow.camera.top=18;sun.shadow.camera.bottom=-18;scene.add(sun);
  mesh(new THREE.CylinderGeometry(15,13,1.4,64),material('#709c89'),scene,0,-.9);const ground=mesh(new THREE.CylinderGeometry(15,15,.14,64),grass,scene,0,-.12);ground.userData.ground=true;targets.push(ground);
  const pathMat=material('#ead6b5'),stone=material('#a9bfc3');
  mesh(new THREE.BoxGeometry(2.3,.035,24),pathMat,scene,0,.005,0);mesh(new THREE.BoxGeometry(23,.035,2.1),pathMat,scene,0,.01,1);mesh(new THREE.BoxGeometry(12,.035,1.5),pathMat,scene,-5,.02,9);mesh(new THREE.BoxGeometry(1.5,.035,8),pathMat,scene,4,.02,5);
  mesh(new THREE.CylinderGeometry(2.5,2.5,.06,40),pathMat,scene,0,.02,0);mesh(new THREE.CylinderGeometry(1.2,1.3,.55,32),stone,scene,0,.3,0);mesh(new THREE.CylinderGeometry(1.07,1.07,.06,32),water,scene,0,.6,0);mesh(new THREE.CylinderGeometry(.22,.3,1.2,16),stone,scene,0,1,0);ball(scene,water,0,1.65,0,.28);
  const pond=mesh(new THREE.CylinderGeometry(3.1,3.1,.12,48),water,scene,-7,.02,4);pond.scale.z=1;
  for(let i=0;i<7;i++){const a=i*2.4;mesh(new THREE.CylinderGeometry(.38,.38,.035,18),leaf,scene,-7+Math.cos(a)*2,.11,4+Math.sin(a)*2);}
  function sign(text:string,x:number,z:number){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=128;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#fff8e4';ctx.fillRect(0,0,512,128);ctx.fillStyle='#385845';ctx.font='bold 38px sans-serif';ctx.textAlign='center';ctx.fillText(text,256,78);const tex=new THREE.CanvasTexture(canvas);resources.push(tex);const m=new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide});resources.push(m);mesh(new THREE.PlaneGeometry(2.8,.7),m,scene,x,1.4,z);mesh(new THREE.CylinderGeometry(.045,.045,1.4,6),wood,scene,x,.7,z);}
  function cottage(x:number,z:number,color:string,title:string){const cabin=new THREE.Group();cabin.position.set(x,0,z);scene.add(cabin);mesh(new THREE.BoxGeometry(3,2.1,2.6),cream,cabin,0,1);const roof=mesh(new THREE.ConeGeometry(2.5,1.5,4),material(color),cabin,0,2.8);roof.rotation.y=Math.PI/4;mesh(new THREE.BoxGeometry(.7,1.3,.12),wood,cabin,0,.65,1.36);for(const wx of [-.95,.95]){mesh(new THREE.BoxGeometry(.55,.6,.14),water,cabin,wx,1.2,1.36);mesh(new THREE.BoxGeometry(.7,.16,.3),wood,cabin,wx,.83,1.4);for(let j=0;j<3;j++)ball(cabin,pink,wx+(j-1)*.18,.98,1.45,.12);}mesh(new THREE.BoxGeometry(.45,1,.45),stone,cabin,.8,3,-.5);sign(title,x,z+2.2);}
  cottage(-7,-7,'#b6a2dd','Willow Cottage');cottage(0,-8,'#dc9fb3','Lily & Lumi');cottage(7,-7,'#83b9c1','Moss Cottage');cottage(-8,-1,'#e5ae70','Honeybun Bakery');
  const stall=new THREE.Group();stall.position.set(9,0,-2);scene.add(stall);mesh(new THREE.BoxGeometry(2.7,.8,1.5),wood,stall,0,.4);for(const x of [-1.2,1.2])mesh(new THREE.CylinderGeometry(.06,.06,2.4,8),wood,stall,x,1.2);mesh(new THREE.BoxGeometry(3,.18,2),pink,stall,0,2.3);for(let i=0;i<5;i++){mesh(new THREE.CylinderGeometry(.18,.13,.3,10),cream,stall,(i-2)*.45,.95);ball(stall,i%2?pink:yellow,(i-2)*.45,1.3,0,.2);}sign('Fern’s Flowers',9,.2);
  for(const [x,z] of [[-11,-5],[-4,-10],[4,-11],[11,-6],[12,4],[9,10],[-11,6],[-4,11]]){const tree=new THREE.Group();scene.add(tree);tree.position.set(x,0,z);mesh(new THREE.CylinderGeometry(.18,.3,2,8),wood,tree,0,1);ball(tree,leaf,0,2.7,0,1.2,1.5,1.2);ball(tree,grass,.6,3.2,.2,.8);}
  for(const [x,z] of [[-10,10],[2,3],[-4,8]]){mesh(new THREE.BoxGeometry(1.6,.15,.6),wood,scene,x,.55,z);mesh(new THREE.BoxGeometry(1.6,.55,.12),wood,scene,x,.9,z-.3);for(const dx of [-.6,.6])mesh(new THREE.BoxGeometry(.12,.5,.4),stone,scene,x+dx,.25,z);}
  sign('Community Garden',6,9.2);
  for(let i=0;i<16;i++){const x=(i%4)*1.4+5,z=(Math.floor(i/4))*1.4+3.2;const bed=mesh(new THREE.BoxGeometry(1.32,.2,1.32),soil,scene,x,.08,z);bed.userData.cell=i;targets.push(bed);beds.push(bed);const plant=new THREE.Group();plant.position.set(x,.2,z);scene.add(plant);mesh(new THREE.CylinderGeometry(.06,.075,.7,8),leaf,plant,0,.35);ball(plant,leaf,-.18,.25,0,.24,.08,.12);ball(plant,leaf,.18,.4,0,.24,.08,.12);const bloom=new THREE.Group();plant.add(bloom);bloom.position.y=.85;const petal=material('#fff2aa');for(let j=0;j<6;j++){const a=j*Math.PI/3;ball(bloom,petal,Math.cos(a)*.24,0,Math.sin(a)*.24,.22,.11,.22);}ball(bloom,yellow,0,.08,0,.15);plant.userData.bloom=bloom;plant.userData.petal=petal;plants.push(plant);}
  const highlight=mesh(new THREE.TorusGeometry(.75,.045,8,40),yellow,scene);highlight.rotation.x=-Math.PI/2;
  function frog(color:string){const f=new THREE.Group(),skin=material(color),eye=material('#253f4c');ball(f,skin,0,.45,0,.43,.36,.35);ball(f,cream,0,.41,.22,.3,.24,.15);for(const x of [-.26,.26]){ball(f,skin,x,.8,.12,.21);ball(f,cream,x,.83,.28,.14);ball(f,eye,x,.84,.4,.065);ball(f,skin,x*1.5,.16,.15,.26,.13,.22);}ball(f,pink,-.34,.57,.31,.09,.04,.03);ball(f,pink,.34,.57,.31,.09,.04,.03);f.userData.weatherCharacter=true;scene.add(f);frogs.push(f);return f;}frog('#5acc98');frog('#bd9ceb');frogs.forEach((f,i)=>{const p=villagePoint(villageSpawn[i]);f.position.set(p.x,0,p.z);});const walkPaths:number[][]=[[],[]],destinations=[-1,-1];
  const rainGeo=new THREE.BufferGeometry(),rainPoints=new Float32Array(150*3);for(let i=0;i<150;i++){rainPoints[i*3]=(Math.random()-.5)*17;rainPoints[i*3+1]=Math.random()*8;rainPoints[i*3+2]=(Math.random()-.5)*14;}rainGeo.setAttribute('position',new THREE.BufferAttribute(rainPoints,3));resources.push(rainGeo);const rainMat=new THREE.PointsMaterial({color:'#d2f3ff',size:.07});resources.push(rainMat);const rain=new THREE.Points(rainGeo,rainMat);scene.add(rain);
  const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let origin={x:0,y:0};const down=(e:PointerEvent)=>{origin={x:e.clientX,y:e.clientY};};const up=(e:PointerEvent)=>{if(Math.hypot(e.clientX-origin.x,e.clientY-origin.y)>12)return;const r=el.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(targets).find(h=>h.object.userData.cell!==undefined)||ray.intersectObjects(targets)[0];if(hit){if(hit.object.userData.cell!==undefined){setCell(hit.object.userData.cell);setPlace(villagePlaces[4]);}else{if(Math.abs(hit.point.x)>12||Math.abs(hit.point.z)>12)return;const target=villageCell(hit.point.x,hit.point.z);if(walkable(target))walkRef.current('walk',target);}}};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointerup',up);
  const lost=(e:Event)=>{e.preventDefault();setFault('3D paused. You can keep gardening with the buttons below.');};renderer.domElement.addEventListener('webglcontextlost',lost);
  const resize=()=>{renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(el);resize();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let frame=0,last=performance.now();
  camera.position.set(9,15,20);
  const disposeWeather=installWeather(renderer,scene,camera);const render=(t:number)=>{frame=requestAnimationFrame(render);if(document.hidden)return;const dt=Math.min(.06,(t-last)/1000);last=t;const {garden:g,cell,clock,view}=current.current;const night=g.weather==='night';renderer.setClearColor(night?'#273d62':g.weather==='rain'?'#9fbdcb':'#b7e6ec');ambient.intensity=night?1.1:2.5;sun.intensity=night?.7:3;const me=current.current.me,focus=view?new THREE.Vector3(0,0,0):frogs[me].position.clone();const zoom=view?1.75:1;const desired=focus.clone().add(new THREE.Vector3(9,15,15).multiplyScalar(zoom*Math.max(1,1/camera.aspect*.68)));camera.position.lerp(desired,1-Math.exp(-dt*4));camera.lookAt(focus.x,0,focus.z);highlight.position.copy(beds[cell].position);highlight.position.y=.23;
   plants.forEach((plant,i)=>{const p=g.plots[i];plant.visible=!!p;if(!p)return;const progress=Math.min(1,Math.max(.15,(clock-p.planted)/Math.max(1000,p.readyAt-p.planted)));plant.scale.setScalar(progress);const bloom=plant.userData.bloom as THREE.Group;bloom.visible=clock>=p.readyAt;const type=seeds.find(s=>s.id===p.seed);(plant.userData.petal as THREE.MeshStandardMaterial).color.set(type?.color||'#fff2aa');plant.rotation.z=reduced?0:Math.sin(t*.0015+i)*.04;});
   frogs.forEach((f,i)=>{const targetCell=g.walkers?.[i]??villageSpawn[i];if(destinations[i]!==targetCell){const start=villageCell(f.position.x,f.position.z);walkPaths[i]=villagePath(walkable(start)?start:villageSpawn[i],targetCell);destinations[i]=targetCell;}const next=walkPaths[i][0];if(next!==undefined){const p=villagePoint(next),dx=p.x-f.position.x,dz=p.z-f.position.z,distance=Math.hypot(dx,dz),step=Math.min(distance,dt*3.4);if(distance<.06){f.position.x=p.x;f.position.z=p.z;walkPaths[i].shift();}else{f.position.x+=dx/distance*step;f.position.z+=dz/distance*step;f.rotation.y=Math.atan2(dx,dz);}f.position.y=reduced?0:Math.abs(Math.sin(t*.013))*.25;}else f.position.y=reduced?0:Math.sin(t*.002+i)*.025;});
   rain.visible=!activeWorld()&&g.weather==='rain'&&!reduced;if(rain.visible){for(let i=0;i<150;i++){rainPoints[i*3+1]-=dt*5;if(rainPoints[i*3+1]<0)rainPoints[i*3+1]=8;}rainGeo.attributes.position.needsUpdate=true;}renderer.render(scene,camera);
  };frame=requestAnimationFrame(render);return()=>{cancelAnimationFrame(frame);observer.disconnect();renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointerup',up);renderer.domElement.removeEventListener('webglcontextlost',lost);resources.forEach(r=>r.dispose());disposeWeather();renderer.dispose();renderer.domElement.remove();};
 },[]);
 const plot=garden.plots[cell],ready=!!plot&&clock>=plot.readyAt,type=seeds.find(s=>s.id===seed)!;
 return <div className="frog-garden"><div className="garden-hud"><span>{state?'🤝 Our village':'🏡 My village · saved on this device'}</span><button onClick={()=>setView(v=>!v)}>{view?'Follow my frog':'Village overview'}</button></div><div className="garden-scene village-scene" ref={host}/><div className="village-guide"><span>Tap open ground to walk · {state?.me===1?'You are Lumi, the purple frog':'You are Lily, the green frog'}</span><nav aria-label="Village places">{villagePlaces.map(p=><button key={p.id} aria-pressed={place.id===p.id} onClick={()=>goTo(p)}>{p.icon} {p.name}{garden.visits?.includes(p.id)?' ✓':''}</button>)}</nav><div className="village-place"><div><b>{place.icon} {place.name}</b><p>{place.text}</p></div><button disabled={busy||(garden.walkers?.[state?.me||0]??villageSpawn[state?.me||0])!==villageCell(place.x,place.z)} onClick={()=>explore('visit',villageCell(place.x,place.z),place.id)}>{garden.visits?.includes(place.id)?'Say hello':'Visit · +2 petals'}</button></div><small>Village passport: {garden.visits?.length||0}/{villagePlaces.length} places discovered. Gardening is below.</small></div><div className="garden-stats"><span>🌸 <b>{garden.coins}</b> petals</span><span>Level <b>{garden.level}</b></span><span>{garden.weather==='rain'?'🌧 Rain boost':garden.weather==='night'?'🌙 Moonlight':'☀ Sunshine'}</span></div><div className="garden-quest"><b>{state?'Grow together: 12 flowers in 3 minutes':`Garden journal · ${garden.harvests} flowers harvested`}</b>{state&&<progress value={garden.harvests} max={12}/>}<p role="status">{garden.log}</p></div>{fault&&<p className="error">{fault}</p>}
 <div className="garden-workbench"><div><label htmlFor="garden-seed">Choose your seeds</label><select id="garden-seed" value={seed} onChange={e=>setSeed(e.target.value)}>{seeds.map(s=><option key={s.id} value={s.id} disabled={s.id==='moon'&&garden.level<2}>{s.name} · {s.cost} petals{s.id==='moon'&&garden.level<2?' · Level 2':''}</option>)}</select></div><div className="plot-info"><b>Plot {cell+1}</b><span>{!plot?'Ready for a seed':ready?'In bloom! Ready to harvest':`${Math.max(1,Math.ceil((plot.readyAt-clock)/1000))} seconds to bloom${plot.watered?' · watered':''}`}</span></div><div className="garden-actions"><button disabled={!loaded||!canPlay||busy||!!plot||garden.coins<type.cost} onClick={()=>move('plant')}>🌱 Plant</button><button disabled={!loaded||!canPlay||busy||!plot||plot.watered||ready} onClick={()=>move('water')}>💧 Water</button><button disabled={!loaded||!canPlay||busy||!ready} onClick={()=>move('harvest')}>🌸 Harvest</button></div><button className="garden-upgrade" disabled={!loaded||!canPlay||busy||garden.level>=3||garden.coins<garden.level*20} onClick={()=>move('upgrade')}>{garden.level>=3?'Garden fully upgraded ✦':`Upgrade garden · ${garden.level*20} petals`}</button>{error&&<p className="error" role="alert">{error}</p>}<details><summary>Choose a plot with buttons</summary><div className="garden-plots">{garden.plots.map((p,i)=><button key={i} aria-pressed={cell===i} aria-label={`Plot ${i+1}, ${p?clock>=p.readyAt?'blooming':p.seed+' growing':'empty'}`} onClick={()=>setCell(i)}>{i+1} {p?clock>=p.readyAt?'🌸':'🌱':'·'}</button>)}</div></details><p className="hint">Rain helps new seeds grow 30% faster. Water once to save 10 seconds. Upgrades make future flowers grow faster.</p></div></div>;
}
