'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import type {GameView} from '@/lib/game';
import {TRACK_LENGTH,newRunner,jumpHeight,runnerSpeed,controlRunner,advanceRunners,hurdle,star,type Runner} from '@/lib/runner';
type Props={state:GameView|null,now:number,onMove:(move:string)=>void};
export default function SkyDash({state,now,onMove}:Props){
 const mount=useRef<HTMLDivElement>(null),live=useRef({state,now,onMove}),practice=useRef<{rs:Runner[],start:number,last:number,running:boolean,winner:number|null}>({rs:[newRunner(),newRunner()],start:0,last:0,running:false,winner:null}),predicted=useRef<{lane?:number,jumpAt?:number,boostUntil?:number,until:number}>({until:0});
 const [failed,setFailed]=useState(''),[loaded,setLoaded]=useState(false),[hud,setHud]=useState({dist:0,other:0,stars:0,hits:0,cooldown:0,practice:false,winner:null as number|null}),[view,setView]=useState<'chase'|'wide'>('chase');const cameraView=useRef(view);
 live.current={state,now,onMove};cameraView.current=view;
 const active=state?!!state.start&&!state.finished&&now>=state.start:hud.practice;
 function move(value:string){const l=live.current,p=practice.current,t=Date.now();if(!l.state){if(p.running)controlRunner(p.rs[0],value,t);return;}if(!l.state.start||l.state.finished||l.now<l.state.start)return;
  const source={...(l.state.runners?.[l.state.me]||newRunner())};if(predicted.current.until>t&&predicted.current.lane!==undefined)source.lane=predicted.current.lane;controlRunner(source,value,l.now);predicted.current={lane:source.lane,jumpAt:source.jumpAt,boostUntil:source.boostUntil,until:t+800};l.onMove(value);
 }
 const input=useRef(move);input.current=move;
 function startPractice(){const t=Date.now();practice.current={rs:[newRunner(),newRunner()],start:t,last:t,running:true,winner:null};predicted.current={until:0};setHud({dist:0,other:0,stars:0,hits:0,cooldown:0,practice:true,winner:null});}
 useEffect(()=>{function key(e:KeyboardEvent){if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||e.target instanceof HTMLSelectElement||(e.target instanceof HTMLElement&&e.target.isContentEditable))return;const command:Record<string,string>={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',Space:'jump',ArrowUp:'jump',KeyW:'jump',ShiftLeft:'boost',ShiftRight:'boost'};if(e.code==='Space'&&e.target instanceof HTMLButtonElement)return;if(command[e.code]&&!e.repeat){e.preventDefault();input.current(command[e.code]);}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{
  const container=mount.current;if(!container)return;let renderer:THREE.WebGLRenderer;
  try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch{setFailed('This browser could not start 3D graphics. Try Chrome, Edge or Safari with hardware acceleration enabled.');return;}
  renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.domElement.setAttribute('aria-label','3D floating garden race with a bunny, a turtle, obstacles and stars');container.appendChild(renderer.domElement);
  const scene=new THREE.Scene();scene.background=new THREE.Color('#a8dded');scene.fog=new THREE.Fog('#b9e7ee',48,115);
  const camera=new THREE.PerspectiveCamera(52,1,.1,250);camera.position.set(8,7,12);
  scene.add(new THREE.HemisphereLight('#fff5de','#64a6a4',2.5));const sun=new THREE.DirectionalLight('#fff2da',3);sun.position.set(-15,30,12);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-22;sun.shadow.camera.right=22;sun.shadow.camera.top=30;sun.shadow.camera.bottom=-30;sun.shadow.camera.far=85;sun.shadow.bias=-.001;scene.add(sun,sun.target);
  const materials=new Map<string,THREE.MeshStandardMaterial>();const mat=(color:string)=>{if(!materials.has(color))materials.set(color,new THREE.MeshStandardMaterial({color,roughness:.78}));return materials.get(color)!;};
  const sphere=new THREE.SphereGeometry(1,16,12),box=new THREE.BoxGeometry(1,1,1),cylinder=new THREE.CylinderGeometry(1,1,1,10),cone=new THREE.ConeGeometry(1,1,7),gem=new THREE.OctahedronGeometry(.38),torus=new THREE.TorusGeometry(.48,.1,7,24);
  function part(parent:THREE.Object3D,geo:THREE.BufferGeometry,color:string,pos:number[],scale:number[]=[1,1,1]){const mesh=new THREE.Mesh(geo,mat(color));mesh.position.set(pos[0],pos[1],pos[2]);mesh.scale.set(scale[0],scale[1],scale[2]);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
  function bunny(){const root=new THREE.Group(),body=new THREE.Group();root.add(body);part(body,sphere,'#fff7ec',[0,.9,0],[.53,.64,.44]);part(body,sphere,'#fffaf2',[0,1.65,-.13],[.58,.52,.48]);part(body,sphere,'#ffb7c9',[-.37,1.51,-.51],[.14,.09,.06]);part(body,sphere,'#ffb7c9',[.37,1.51,-.51],[.14,.09,.06]);part(body,sphere,'#dd829f',[0,1.49,-.62],[.08,.06,.04]);
   for(const x of [-.23,.23]){part(body,sphere,'#252b43',[x,1.71,-.55],[.07,.1,.055]);part(body,sphere,'#ffffff',[x-.018,1.74,-.601],[.022,.025,.015]);}
   const ears=[-1,1].map(side=>{const e=new THREE.Group();e.position.set(side*.25,2,-.08);part(e,sphere,'#fffaf2',[0,.42,0],[.16,.57,.14]);part(e,sphere,'#f8a9c3',[0,.43,-.12],[.085,.39,.026]);body.add(e);return e;});
   const feet=[-1,1].map(side=>part(body,sphere,'#f3e4e3',[side*.31,.26,-.12],[.23,.22,.37]));const arms=[-1,1].map(side=>part(body,sphere,'#fff4e9',[side*.48,.93,-.04],[.18,.33,.18]));part(body,sphere,'#ffffff',[0,.62,.42],[.25,.25,.22]);const scarf=part(body,torus,'#e66f9e',[0,1.3,-.04],[.85,1,.85]);scarf.rotation.x=Math.PI/2;part(body,box,'#e66f9e',[.31,1.06,.24],[.19,.47,.1]);return {root,body,ears,feet,arms};
  }
  function turtle(){const root=new THREE.Group(),body=new THREE.Group();root.add(body);part(body,sphere,'#6c9b68',[0,.55,0],[.7,.28,.84]);part(body,sphere,'#397963',[0,.85,.04],[.67,.55,.79]);part(body,sphere,'#73b879',[0,1.07,.01],[.46,.34,.55]);for(const x of [-1,1])for(const z of [-1,1])part(body,sphere,'#8eca8d',[x*.41,.9,z*.39],[.2,.17,.23]);part(body,sphere,'#a8d78e',[0,.8,-.9],[.41,.35,.4]);for(const x of [-.2,.2]){part(body,sphere,'#ffffff',[x,.94,-1.19],[.12,.13,.065]);part(body,sphere,'#243d3c',[x,.95,-1.245],[.05,.065,.025]);}const feet=[-1,1].flatMap(x=>[-1,1].map(z=>part(body,sphere,'#9ecf83',[x*.61,.3,z*.52],[.24,.2,.33])));part(body,cone,'#a8d78e',[0,.44,.94],[.16,.35,.16]).rotation.x=Math.PI/2;const band=part(body,torus,'#f2c555',[0,.85,-.69],[.57,.57,.57]);band.rotation.x=Math.PI/2;return {root,body,ears:[] as THREE.Object3D[],feet,arms:[] as THREE.Object3D[]};}
  const chars=[bunny(),turtle()];chars.forEach(c=>scene.add(c.root));
  // A real world-space course: floating islands, three lanes and physical hurdles.
  part(scene,box,'#d9b1e1',[0,-.45,-125],[10,.9,280]);part(scene,box,'#fff0d0',[0,.035,-125],[7.8,.13,280]);for(const x of [-3.85,3.85])part(scene,box,'#f393b6',[x,.17,-125],[.12,.28,280]);for(const x of [-1.2,1.2])for(let z=0;z<255;z+=4)part(scene,box,'#e3bdda',[x,.115,-z],[.075,.03,1.7]);
  for(let i=0;i<42;i++){const side=i%2?1:-1,z=8-i*6.3,x=side*(7+(i%4)*1.3),size=2.2+(i%3)*.5;part(scene,sphere,'#7bbaa0',[x,-1.7,z],[size,1.8,size*1.45]);part(scene,sphere,'#ade0a7',[x,-.35,z],[size*.96,.6,size*1.35]);const trunk=part(scene,cylinder,'#987b71',[x,1,z],[.18,2,.18]);for(let k=0;k<3;k++)part(scene,sphere,i%3===0?'#f3b4cd':i%3===1?'#87cfa7':'#b6abe8',[x+(k-1)*.5,2.3+(k%2)*.55,z],[.95,1.2,.9]);if(i%3===0)part(scene,sphere,'#fff5e8',[x+.9,.55,z+.6],[.55,.32,.55]);}
  const clouds:THREE.Group[]=[];for(let i=0;i<16;i++){const g=new THREE.Group();g.position.set((i%2?1:-1)*(15+i%4*3),7+i%3*2,-i*18);for(let j=0;j<4;j++){const m=part(g,sphere,'#fff6f6',[(j-1.5)*1.2,Math.sin(j)*.4,0],[1.8,1,1]);m.castShadow=false;}scene.add(g);clouds.push(g);}
  const hurdles:THREE.Group[]=[];for(let i=0;i<14;i++){const g=new THREE.Group();for(const x of [-.68,.68])part(g,cylinder,'#9b799b',[x,.48,0],[.09,.95,.09]);part(g,box,'#ef99aa',[0,.61,0],[1.65,.43,.2]);for(const x of [-.52,0,.52])part(g,box,'#fff6d8',[x,.615,-.11],[.2,.43,.025]);scene.add(g);hurdles.push(g);}
  const stars:THREE.Mesh[]=[];for(let i=0;i<20;i++){const m=part(scene,gem,'#ffd25f',[0,1,-10]);(m.material as THREE.MeshStandardMaterial).emissive=new THREE.Color('#6b3900');stars.push(m);}
  const finish=new THREE.Group();for(const x of [-4,4])part(finish,cylinder,'#9268b9',[x,2.5,0],[.16,5,.16]);part(finish,box,'#f6cf65',[0,4.8,0],[8.3,.65,.25]);for(let i=0;i<16;i++)for(let j=0;j<2;j++)part(finish,box,(i+j)%2?'#765282':'#fff6e9',[-3.75+i*.5,.17,j*.5],[.5,.12,.5]);finish.position.z=-TRACK_LENGTH;scene.add(finish);
  const ring=part(scene,new THREE.TorusGeometry(.85,.04,6,40),'#dc8de1',[0,.12,0]);ring.rotation.x=Math.PI/2;
  const particles:THREE.Mesh[]=[];for(let i=0;i<28;i++){const m=part(scene,new THREE.BoxGeometry(.12,.12,.12),['#f5b24c','#fa85bb','#87d6c2','#b394e8'][i%4],[0,-50,0]);m.castShadow=false;particles.push(m);}
  let disposed=false,frame=0,last=performance.now(),lastHud=0,initial=true,lastRound=-1;const positions=[0,0],xs=[-.45,.45],look=new THREE.Vector3();
  const resize=new ResizeObserver(()=>{const w=container.clientWidth,h=container.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();});resize.observe(container);
  const contextLost=(e:Event)=>{e.preventDefault();setFailed('3D graphics paused. Reload the page to restore the game.');};renderer.domElement.addEventListener('webglcontextlost',contextLost);
  function animate(ms:number){if(disposed)return;frame=requestAnimationFrame(animate);const delta=Math.min((ms-last)/1000,.05);last=ms;const l=live.current,p=practice.current,wall=Date.now(),s=l.state;let rs:Runner[],running:boolean,round:number,me:number,t:number;
   if(s){rs=s.runners||[newRunner(),newRunner()];running=!!s.start&&!s.finished&&l.now>=s.start;round=s.round;me=s.me;t=l.now;if(round!==lastRound){positions[0]=positions[1]=0;lastRound=round;predicted.current={until:0};}}
   else {rs=p.rs;running=p.running;round=1;me=0;t=wall;if(p.running){const other=rs[1],next=hurdle(other.lastObstacle+1,1);if(next.distance-other.distance<4&&next.lane===other.lane&&wall-other.jumpAt>1400)controlRunner(other,'jump',wall);if(wall>=other.boostReadyAt+2000)controlRunner(other,'boost',wall);const outcome=advanceRunners(rs,p.last,wall,1);p.last=wall;if(outcome){p.running=false;p.winner=outcome.winner;}}}
   const attract=!s&&!p.start;const pred=predicted.current;
   chars.forEach((c,i)=>{const r=rs[i]||newRunner(),distance=r.distance;const lead=s&&running?Math.min(.55,Math.max(0,(l.now-(s.raceAt||l.now))/1000))*runnerSpeed(r,t):0;const target=distance+lead;positions[i]=THREE.MathUtils.damp(positions[i],target,12,delta);let lane=r.lane,jump=jumpHeight(r,t);if(s&&i===me&&pred.until>wall){lane=pred.lane??lane;if(pred.jumpAt)jump=Math.max(jump,jumpHeight({...r,jumpAt:pred.jumpAt},t));}const sway=running?Math.sin(ms*.016+i)*.045:Math.sin(ms*.002+i)*.025;xs[i]=THREE.MathUtils.damp(xs[i],lane*2.4+(i===0?-.37:.37),13,delta);c.root.position.set(xs[i],jump+(i===0&&running?Math.abs(Math.sin(ms*.017))*.15:0),-positions[i]);c.root.rotation.y=attract?Math.sin(ms*.0004)*.2+Math.PI*.12:-(lane*2.4+(i===0?-.37:.37)-xs[i])*.15;c.body.rotation.z=sway;c.body.rotation.x=running&&t<r.boostUntil?-.17:0;c.ears.forEach((e,j)=>{e.rotation.z=(j?1:-1)*(.12+Math.sin(ms*.009)*.045);e.rotation.x=running?Math.sin(ms*.013)*.11:.04;});c.feet.forEach((f,j)=>{f.rotation.x=running?Math.sin(ms*.022+j*Math.PI)*.42:0;});c.arms.forEach((a,j)=>a.rotation.x=running?Math.sin(ms*.02+j*Math.PI)*.6:0);if(t<r.slowUntil){c.body.rotation.z=Math.sin(ms*.06)*.15;}});
   hurdles.forEach((g,i)=>{const h=hurdle(i,round);g.position.set(h.lane*2.4,0,-h.distance);});stars.forEach((m,i)=>{const item=star(i,round);m.position.set(item.lane*2.4,1.1+Math.sin(ms*.003+i)*.18,-item.distance);m.rotation.y=ms*.002+i;m.rotation.z=Math.PI/4;m.visible=rs[me].distance<item.distance-.5;});clouds.forEach((c,i)=>c.position.x+=(Math.sin(ms*.00015+i)*.001));
   const z=positions[me];ring.position.set(xs[me],.14,-z);ring.visible=!attract;const wide=cameraView.current==='wide';const desired=new THREE.Vector3(attract?Math.sin(ms*.00025)*3+7:wide?10:xs[me]*.42,attract?6:wide?8:5.2,attract?11:-z+(wide?12:10));camera.position.lerp(desired,initial?1:1-Math.exp(-4*delta));look.set(attract?0:xs[me]*.3,attract?1:.9,attract?-4:-z-9);camera.lookAt(look);initial=false;sun.position.set(-15,28,-z+12);sun.target.position.set(0,0,-z-15);
   const celebration=s?.finished||(!s&&p.winner!==null),boosting=running&&t<rs[me].boostUntil;particles.forEach((m,i)=>{m.visible=!!celebration||boosting;if(m.visible){if(celebration)m.position.set(Math.sin(i*3.7)*5,((ms*.002+i*.34)%6)+.5,-z+Math.cos(i*2)*4);else m.position.set(xs[me]+Math.sin(i*8)*.6,((i%5)*.12)+.2,-z+.6+(ms*.008+i*.3)%4);m.rotation.x=ms*.003+i;m.rotation.z=ms*.002+i;}});
   renderer.render(scene,camera);if(ms-lastHud>100){lastHud=ms;setHud({dist:rs[me].distance,other:rs[1-me].distance,stars:rs[me].stars,hits:rs[me].hits,cooldown:Math.max(0,Math.ceil((rs[me].boostReadyAt-t)/1000)),practice:p.running,winner:p.winner});}
  }
  // live.now is refreshed by the parent clock; the render loop interpolates positions.
  frame=requestAnimationFrame(animate);setLoaded(true);
  return()=>{disposed=true;cancelAnimationFrame(frame);resize.disconnect();renderer.domElement.removeEventListener('webglcontextlost',contextLost);scene.traverse(o=>{const m=o as THREE.Mesh;if(m.geometry)m.geometry.dispose();});materials.forEach(m=>m.dispose());renderer.dispose();renderer.domElement.remove();};
 },[]);
 return <div className="sky-game">
  <div className="sky-viewport"><div className="sky-canvas" ref={mount}/>{!loaded&&!failed&&<div className="sky-message">Opening the floating gardens…</div>}{failed&&<div className="sky-message">{failed}</div>}
   <div className="sky-top"><span className="sky-badge">SKY DASH <small>3D</small></span><button className="sky-view" onClick={()=>setView(view==='chase'?'wide':'chase')} aria-label="Change camera view">{view==='chase'?'Wide camera':'Chase camera'}</button></div>
   <div className="sky-stats"><span>⭐ {hud.stars}</span><span>{Math.floor(hud.dist)} <small>/ {TRACK_LENGTH} m</small></span></div>
   {!state&&!hud.practice&&<div className="sky-start"><span className="sky-kicker">THE FLOATING GARDENS</span><h3>{hud.winner!==null?(hud.winner===0?'You won!':hud.winner===-1?'Photo finish!':'Turtle wins!'):'A little adventure.\nA proper race.'}</h3><p>Jump. Dodge. Boost. Beat your favourite rival.</p><button onClick={startPractice}>{hud.winner!==null?'Race again':'Try solo practice'} <span>▶</span></button><small>Create a room to race your partner online.</small></div>}
   {state&&!!state.start&&!state.finished&&now<state.start&&<div className="sky-count">{Math.ceil((state.start-now)/1000)}</div>}
   <div className="sky-position"><span>{state?.players[state.me]?.name||'You'}</span><div><i style={{width:`${hud.dist/TRACK_LENGTH*100}%`}}/></div><span>{state?.players[1-state.me]?.name||'Turtle'}</span><div><i className="rival" style={{width:`${hud.other/TRACK_LENGTH*100}%`}}/></div></div>
  </div>
  <div className="sky-controls"><button disabled={!active} onClick={()=>move('left')} aria-label="Move left">←<small>A / ←</small></button><button className="jump-control" disabled={!active} onClick={()=>move('jump')}>JUMP<small>Space / ↑</small></button><button disabled={!active} onClick={()=>move('right')} aria-label="Move right">→<small>D / →</small></button><button className="boost-control" disabled={!active||hud.cooldown>0} onClick={()=>move('boost')}>{hud.cooldown?`${hud.cooldown}s`:'BOOST'}<small>Shift ⚡</small></button></div>
  <p className="sky-help">Jump over pink hurdles · change lanes to collect stars · boost recharges every 6.5 seconds</p>
 </div>;
}
